# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: takasho/schema/common_featureset/resource/player_achievement/v1.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from takasho.schema.common_featureset.resource.achievement import v1_pb2 as takasho_dot_schema_dot_common__featureset_dot_resource_dot_achievement_dot_v1__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nEtakasho/schema/common_featureset/resource/player_achievement/v1.proto\x12?takasho.schema.common_featureset.resource.player_achievement.v1\x1a>takasho/schema/common_featureset/resource/achievement/v1.proto\"\x89\x01\n\x11PlayerAchievement\x12Z\n\x0b\x61\x63hievement\x18\x01 \x01(\x0b\x32\x45.takasho.schema.common_featureset.resource.achievement.v1.Achievement\x12\x18\n\x10last_unlocked_at\x18\x02 \x01(\x12\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'takasho.schema.common_featureset.resource.player_achievement.v1_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PLAYERACHIEVEMENT._serialized_start=203
  _PLAYERACHIEVEMENT._serialized_end=340
# @@protoc_insertion_point(module_scope)
