# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: takasho/schema/fes/resource/player_regular_ranking/v1.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n;takasho/schema/fes/resource/player_regular_ranking/v1.proto\x12\x35takasho.schema.fes.resource.player_regular_ranking.v1\"n\n\x14PlayerRegularRanking\x12\x13\n\x0branking_key\x18\x01 \x01(\t\x12\x11\n\tplayer_id\x18\x02 \x01(\t\x12\x11\n\tnick_name\x18\x03 \x01(\t\x12\x0c\n\x04rank\x18\x04 \x01(\x03\x12\r\n\x05score\x18\x05 \x01(\x03\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'takasho.schema.fes.resource.player_regular_ranking.v1_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PLAYERREGULARRANKING._serialized_start=118
  _PLAYERREGULARRANKING._serialized_end=228
# @@protoc_insertion_point(module_scope)
