# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: takasho/schema/fes/player_api/subscription/renewal_reward.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from takasho.schema.fes.resource.subscription.renewal_reward import v1_pb2 as takasho_dot_schema_dot_fes_dot_resource_dot_subscription_dot_renewal__reward_dot_v1__pb2
from takasho.schema.common_featureset.resource.player_inventory import v1_pb2 as takasho_dot_schema_dot_common__featureset_dot_resource_dot_player__inventory_dot_v1__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n?takasho/schema/fes/player_api/subscription/renewal_reward.proto\x12\x39takasho.schema.fes.player_api.subscription.renewal_reward\x1a@takasho/schema/fes/resource/subscription/renewal_reward/v1.proto\x1a\x43takasho/schema/common_featureset/resource/player_inventory/v1.proto\"\x98\x01\n\x1bRenewalRewardGetAvailableV1\x1a\t\n\x07Request\x1an\n\x08Response\x12\x62\n\x0frenewal_rewards\x18\x01 \x03(\x0b\x32I.takasho.schema.fes.resource.subscription.renewal_reward.v1.RenewalReward\"\xdb\x02\n\x16RenewalRewardReceiveV1\x1a\t\n\x07Request\x1a\xb5\x02\n\x08Response\x12\x62\n\x0frenewal_rewards\x18\x01 \x03(\x0b\x32I.takasho.schema.fes.resource.subscription.renewal_reward.v1.RenewalReward\x12\x63\n\x0binventories\x18\x02 \x03(\x0b\x32N.takasho.schema.common_featureset.resource.player_inventory.v1.PlayerInventory\x12`\n\x0erenewal_counts\x18\x03 \x03(\x0b\x32H.takasho.schema.fes.resource.subscription.renewal_reward.v1.RenewalCount2\xac\x03\n\rRenewalReward\x12\xd3\x01\n\x0eGetAvailableV1\x12^.takasho.schema.fes.player_api.subscription.renewal_reward.RenewalRewardGetAvailableV1.Request\x1a_.takasho.schema.fes.player_api.subscription.renewal_reward.RenewalRewardGetAvailableV1.Response\"\x00\x12\xc4\x01\n\tReceiveV1\x12Y.takasho.schema.fes.player_api.subscription.renewal_reward.RenewalRewardReceiveV1.Request\x1aZ.takasho.schema.fes.player_api.subscription.renewal_reward.RenewalRewardReceiveV1.Response\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'takasho.schema.fes.player_api.subscription.renewal_reward_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RENEWALREWARDGETAVAILABLEV1._serialized_start=262
  _RENEWALREWARDGETAVAILABLEV1._serialized_end=414
  _RENEWALREWARDGETAVAILABLEV1_REQUEST._serialized_start=293
  _RENEWALREWARDGETAVAILABLEV1_REQUEST._serialized_end=302
  _RENEWALREWARDGETAVAILABLEV1_RESPONSE._serialized_start=304
  _RENEWALREWARDGETAVAILABLEV1_RESPONSE._serialized_end=414
  _RENEWALREWARDRECEIVEV1._serialized_start=417
  _RENEWALREWARDRECEIVEV1._serialized_end=764
  _RENEWALREWARDRECEIVEV1_REQUEST._serialized_start=293
  _RENEWALREWARDRECEIVEV1_REQUEST._serialized_end=302
  _RENEWALREWARDRECEIVEV1_RESPONSE._serialized_start=455
  _RENEWALREWARDRECEIVEV1_RESPONSE._serialized_end=764
  _RENEWALREWARD._serialized_start=767
  _RENEWALREWARD._serialized_end=1195
# @@protoc_insertion_point(module_scope)
