# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from takasho.schema.fes.player_api.subscription import renewal_reward_pb2 as takasho_dot_schema_dot_fes_dot_player__api_dot_subscription_dot_renewal__reward__pb2


class RenewalRewardStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAvailableV1 = channel.unary_unary(
                '/takasho.schema.fes.player_api.subscription.renewal_reward.RenewalReward/GetAvailableV1',
                request_serializer=takasho_dot_schema_dot_fes_dot_player__api_dot_subscription_dot_renewal__reward__pb2.RenewalRewardGetAvailableV1.Request.SerializeToString,
                response_deserializer=takasho_dot_schema_dot_fes_dot_player__api_dot_subscription_dot_renewal__reward__pb2.RenewalRewardGetAvailableV1.Response.FromString,
                )
        self.ReceiveV1 = channel.unary_unary(
                '/takasho.schema.fes.player_api.subscription.renewal_reward.RenewalReward/ReceiveV1',
                request_serializer=takasho_dot_schema_dot_fes_dot_player__api_dot_subscription_dot_renewal__reward__pb2.RenewalRewardReceiveV1.Request.SerializeToString,
                response_deserializer=takasho_dot_schema_dot_fes_dot_player__api_dot_subscription_dot_renewal__reward__pb2.RenewalRewardReceiveV1.Response.FromString,
                )


class RenewalRewardServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAvailableV1(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReceiveV1(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RenewalRewardServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAvailableV1': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAvailableV1,
                    request_deserializer=takasho_dot_schema_dot_fes_dot_player__api_dot_subscription_dot_renewal__reward__pb2.RenewalRewardGetAvailableV1.Request.FromString,
                    response_serializer=takasho_dot_schema_dot_fes_dot_player__api_dot_subscription_dot_renewal__reward__pb2.RenewalRewardGetAvailableV1.Response.SerializeToString,
            ),
            'ReceiveV1': grpc.unary_unary_rpc_method_handler(
                    servicer.ReceiveV1,
                    request_deserializer=takasho_dot_schema_dot_fes_dot_player__api_dot_subscription_dot_renewal__reward__pb2.RenewalRewardReceiveV1.Request.FromString,
                    response_serializer=takasho_dot_schema_dot_fes_dot_player__api_dot_subscription_dot_renewal__reward__pb2.RenewalRewardReceiveV1.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'takasho.schema.fes.player_api.subscription.renewal_reward.RenewalReward', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RenewalReward(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAvailableV1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/takasho.schema.fes.player_api.subscription.renewal_reward.RenewalReward/GetAvailableV1',
            takasho_dot_schema_dot_fes_dot_player__api_dot_subscription_dot_renewal__reward__pb2.RenewalRewardGetAvailableV1.Request.SerializeToString,
            takasho_dot_schema_dot_fes_dot_player__api_dot_subscription_dot_renewal__reward__pb2.RenewalRewardGetAvailableV1.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReceiveV1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/takasho.schema.fes.player_api.subscription.renewal_reward.RenewalReward/ReceiveV1',
            takasho_dot_schema_dot_fes_dot_player__api_dot_subscription_dot_renewal__reward__pb2.RenewalRewardReceiveV1.Request.SerializeToString,
            takasho_dot_schema_dot_fes_dot_player__api_dot_subscription_dot_renewal__reward__pb2.RenewalRewardReceiveV1.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
