# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: takasho/schema/common_featureset/resource/announcement/v1.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n?takasho/schema/common_featureset/resource/announcement/v1.proto\x12\x39takasho.schema.common_featureset.resource.announcement.v1\"\xd7\x01\n\x0c\x41nnouncement\x12\n\n\x02id\x18\x01 \x01(\t\x12\x15\n\rlanguage_code\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12\x11\n\topened_at\x18\x04 \x01(\x12\x12\x11\n\tclosed_at\x18\x05 \x01(\x12\x12\r\n\x05value\x18\x06 \x01(\x0c\x12`\n\x08\x63ontents\x18\x07 \x03(\x0b\x32N.takasho.schema.common_featureset.resource.announcement.v1.AnnouncementContent\"8\n\x13\x41nnouncementContent\x12\x12\n\nschema_key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'takasho.schema.common_featureset.resource.announcement.v1_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ANNOUNCEMENT._serialized_start=127
  _ANNOUNCEMENT._serialized_end=342
  _ANNOUNCEMENTCONTENT._serialized_start=344
  _ANNOUNCEMENTCONTENT._serialized_end=400
# @@protoc_insertion_point(module_scope)
