# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: takasho/schema/fes/resource/club_storage/v1.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1takasho/schema/fes/resource/club_storage/v1.proto\x12+takasho.schema.fes.resource.club_storage.v1\"?\n\x10\x43lubStorageEntry\x12\x0f\n\x07\x63lub_id\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\x0c\"\x9c\x01\n\tCriterion\x12\x0b\n\x03key\x18\x01 \x01(\t\x12Z\n\rmatching_type\x18\x02 \x01(\x0e\x32\x43.takasho.schema.fes.resource.club_storage.v1.Criterion.MatchingType\"&\n\x0cMatchingType\x12\t\n\x05\x45XACT\x10\x00\x12\x0b\n\x07\x46ORWARD\x10\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'takasho.schema.fes.resource.club_storage.v1_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CLUBSTORAGEENTRY._serialized_start=98
  _CLUBSTORAGEENTRY._serialized_end=161
  _CRITERION._serialized_start=164
  _CRITERION._serialized_end=320
  _CRITERION_MATCHINGTYPE._serialized_start=282
  _CRITERION_MATCHINGTYPE._serialized_end=320
# @@protoc_insertion_point(module_scope)
