# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: takasho/schema/common_featureset/resource/achievement/v1.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from takasho.schema.common_featureset.resource.player_inventory import v1_pb2 as takasho_dot_schema_dot_common__featureset_dot_resource_dot_player__inventory_dot_v1__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n>takasho/schema/common_featureset/resource/achievement/v1.proto\x12\x38takasho.schema.common_featureset.resource.achievement.v1\x1a\x43takasho/schema/common_featureset/resource/player_inventory/v1.proto\"\xd9\x02\n\x0b\x41\x63hievement\x12\x16\n\x0e\x61\x63hievement_id\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c\x12\x11\n\topened_at\x18\x04 \x01(\x12\x12\x11\n\tclosed_at\x18\x05 \x01(\x12\x12W\n\nreset_type\x18\x06 \x01(\x0e\x32\x43.takasho.schema.common_featureset.resource.achievement.v1.ResetType\x12\x11\n\tdate_line\x18\x07 \x01(\t\x12\x13\n\x0b\x64\x61y_of_week\x18\x08 \x01(\x12\x12Z\n\x06prizes\x18\x0b \x03(\x0b\x32J.takasho.schema.common_featureset.resource.achievement.v1.AchievementPrize\x12\x10\n\x08\x63\x61tegory\x18\x0c \x01(\t\x12\x0e\n\x06unlock\x18\r \x01(\x08\"\x98\x02\n\x10\x41\x63hievementPrize\x12\x16\n\x0e\x61\x63hievement_id\x18\x01 \x01(\t\x12\x1c\n\x14\x61\x63hievement_prize_id\x18\x02 \x01(\t\x12Z\n\titem_type\x18\x04 \x01(\x0e\x32G.takasho.schema.common_featureset.resource.player_inventory.v1.ItemType\x12\x12\n\nschema_key\x18\x05 \x01(\t\x12\r\n\x05value\x18\x06 \x01(\x0c\x12\x14\n\x0csearch_label\x18\x07 \x01(\t\x12\x1c\n\x14system_resource_name\x18\x08 \x01(\t\x12\x1b\n\x13system_resource_num\x18\t \x01(\x12\"\x1d\n\tCriterion\x12\x10\n\x08\x63\x61tegory\x18\x01 \x01(\t*3\n\tResetType\x12\x08\n\x04NONE\x10\x00\x12\r\n\tDATE_LINE\x10\x01\x12\r\n\tWEEK_LINE\x10\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'takasho.schema.common_featureset.resource.achievement.v1_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RESETTYPE._serialized_start=855
  _RESETTYPE._serialized_end=906
  _ACHIEVEMENT._serialized_start=194
  _ACHIEVEMENT._serialized_end=539
  _ACHIEVEMENTPRIZE._serialized_start=542
  _ACHIEVEMENTPRIZE._serialized_end=822
  _CRITERION._serialized_start=824
  _CRITERION._serialized_end=853
# @@protoc_insertion_point(module_scope)
