# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: takasho/schema/common_featureset/resource/login_bonus/v1.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from takasho.schema.common_featureset.resource.player_inventory import v1_pb2 as takasho_dot_schema_dot_common__featureset_dot_resource_dot_player__inventory_dot_v1__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n>takasho/schema/common_featureset/resource/login_bonus/v1.proto\x12\x38takasho.schema.common_featureset.resource.login_bonus.v1\x1a\x43takasho/schema/common_featureset/resource/player_inventory/v1.proto\"\xe9\x02\n\nLoginBonus\x12\x16\n\x0elogin_bonus_id\x18\x01 \x01(\t\x12\x11\n\topened_at\x18\x04 \x01(\x12\x12\x11\n\tclosed_at\x18\x05 \x01(\x12\x12W\n\nreset_type\x18\x06 \x01(\x0e\x32\x43.takasho.schema.common_featureset.resource.login_bonus.v1.ResetType\x12\x11\n\tdate_line\x18\x07 \x01(\t\x12\x12\n\ntime_lapse\x18\x08 \x01(\x12\x12\x18\n\x10last_prize_count\x18\t \x01(\x12\x12\x1a\n\x12last_counted_up_at\x18\n \x01(\x12\x12Y\n\x06prizes\x18\x0b \x03(\x0b\x32I.takasho.schema.common_featureset.resource.login_bonus.v1.LoginBonusPrize\x12\x0c\n\x04loop\x18\x0c \x01(\x08\"\x9e\x02\n\x0fLoginBonusPrize\x12\x16\n\x0elogin_bonus_id\x18\x01 \x01(\t\x12\x1c\n\x14login_bonus_prize_id\x18\x02 \x01(\t\x12\x13\n\x0bprize_count\x18\x03 \x01(\x12\x12Z\n\titem_type\x18\x04 \x01(\x0e\x32G.takasho.schema.common_featureset.resource.player_inventory.v1.ItemType\x12\x12\n\nschema_key\x18\x05 \x01(\t\x12\r\n\x05value\x18\x06 \x01(\x0c\x12\x14\n\x0csearch_label\x18\x07 \x01(\t\x12\x15\n\rresource_name\x18\x08 \x01(\t\x12\x14\n\x0cresource_num\x18\t \x01(\x12**\n\tResetType\x12\r\n\tDATE_LINE\x10\x00\x12\x0e\n\nTIME_LAPSE\x10\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'takasho.schema.common_featureset.resource.login_bonus.v1_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RESETTYPE._serialized_start=846
  _RESETTYPE._serialized_end=888
  _LOGINBONUS._serialized_start=194
  _LOGINBONUS._serialized_end=555
  _LOGINBONUSPRIZE._serialized_start=558
  _LOGINBONUSPRIZE._serialized_end=844
# @@protoc_insertion_point(module_scope)
