# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: takasho/schema/fes/resource/friend/v1.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from takasho.schema.common_featureset.resource.player_storage import v2_pb2 as takasho_dot_schema_dot_common__featureset_dot_resource_dot_player__storage_dot_v2__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+takasho/schema/fes/resource/friend/v1.proto\x12%takasho.schema.fes.resource.friend.v1\x1a\x41takasho/schema/common_featureset/resource/player_storage/v2.proto\"\x8a\x05\n\tCriterion\x12P\n\x0border_field\x18\x01 \x01(\x0e\x32;.takasho.schema.fes.resource.friend.v1.Criterion.OrderField\x12X\n\x0forder_direction\x18\x02 \x01(\x0e\x32?.takasho.schema.fes.resource.friend.v1.Criterion.OrderDirection\x12G\n\x06\x66ilter\x18\x03 \x01(\x0b\x32\x37.takasho.schema.fes.resource.friend.v1.Criterion.Filter\x1a\x92\x02\n\x06\x46ilter\x12N\n\x06\x66ollow\x18\x01 \x01(\x0e\x32>.takasho.schema.fes.resource.friend.v1.Criterion.Filter.Follow\x12J\n\x04\x63lub\x18\x02 \x01(\x0e\x32<.takasho.schema.fes.resource.friend.v1.Criterion.Filter.Club\"4\n\x06\x46ollow\x12\x0e\n\nALL_FOLLOW\x10\x00\x12\n\n\x06MUTUAL\x10\x01\x12\x0e\n\nNOT_MUTUAL\x10\x02\"6\n\x04\x43lub\x12\x0c\n\x08\x41LL_CLUB\x10\x00\x12\r\n\tSAME_CLUB\x10\x01\x12\x11\n\rNOT_SAME_CLUB\x10\x02\"N\n\nOrderField\x12\x17\n\x13UNKNOWN_ORDER_FIELD\x10\x00\x12\x15\n\x11LAST_LOGGED_IN_AT\x10\x01\x12\x10\n\x0cPLAYER_LEVEL\x10\x02\"#\n\x0eOrderDirection\x12\x07\n\x03\x41SC\x10\x00\x12\x08\n\x04\x44\x45SC\x10\x01\"\xf1\x01\n\x0c\x46riendPlayer\x12\x11\n\tplayer_id\x18\x01 \x01(\t\x12\x62\n\x16player_storage_entries\x18\x02 \x03(\x0b\x32\x42.takasho.schema.common_featureset.resource.player_storage.v2.Entry\x12\x10\n\x08nickname\x18\x03 \x01(\t\x12\x12\n\nclub_names\x18\x04 \x03(\t\x12\x14\n\x0cis_following\x18\x05 \x01(\x08\x12\x13\n\x0bis_followed\x18\x06 \x01(\x08\x12\x19\n\x11last_logged_in_at\x18\x07 \x01(\x12\"L\n\x0c\x46ollowStatus\x12\x11\n\tplayer_id\x18\x01 \x01(\t\x12\x14\n\x0cis_following\x18\x02 \x01(\x08\x12\x13\n\x0bis_followed\x18\x03 \x01(\x08\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'takasho.schema.fes.resource.friend.v1_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CRITERION._serialized_start=154
  _CRITERION._serialized_end=804
  _CRITERION_FILTER._serialized_start=413
  _CRITERION_FILTER._serialized_end=687
  _CRITERION_FILTER_FOLLOW._serialized_start=579
  _CRITERION_FILTER_FOLLOW._serialized_end=631
  _CRITERION_FILTER_CLUB._serialized_start=633
  _CRITERION_FILTER_CLUB._serialized_end=687
  _CRITERION_ORDERFIELD._serialized_start=689
  _CRITERION_ORDERFIELD._serialized_end=767
  _CRITERION_ORDERDIRECTION._serialized_start=769
  _CRITERION_ORDERDIRECTION._serialized_end=804
  _FRIENDPLAYER._serialized_start=807
  _FRIENDPLAYER._serialized_end=1048
  _FOLLOWSTATUS._serialized_start=1050
  _FOLLOWSTATUS._serialized_end=1126
# @@protoc_insertion_point(module_scope)
