# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: takasho/schema/fes/resource/subscription/renewal_reward/v1.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from takasho.schema.common_featureset.resource.player_inventory import v1_pb2 as takasho_dot_schema_dot_common__featureset_dot_resource_dot_player__inventory_dot_v1__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n@takasho/schema/fes/resource/subscription/renewal_reward/v1.proto\x12:takasho.schema.fes.resource.subscription.renewal_reward.v1\x1a\x43takasho/schema/common_featureset/resource/player_inventory/v1.proto\"\xda\x01\n\rRenewalReward\x12\x11\n\treward_id\x18\x01 \x01(\t\x12\x1f\n\x17subscription_product_id\x18\x02 \x01(\t\x12\x11\n\topened_at\x18\x03 \x01(\x12\x12\x11\n\tclosed_at\x18\x04 \x01(\x12\x12^\n\x06prizes\x18\x05 \x03(\x0b\x32N.takasho.schema.fes.resource.subscription.renewal_reward.v1.RenewalRewardPrize\x12\x0f\n\x07is_loop\x18\x06 \x01(\x08\"\x8c\x02\n\x12RenewalRewardPrize\x12\x17\n\x0freward_prize_id\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x12\x12Z\n\titem_type\x18\x03 \x01(\x0e\x32G.takasho.schema.common_featureset.resource.player_inventory.v1.ItemType\x12\x12\n\nschema_key\x18\x04 \x01(\t\x12\r\n\x05value\x18\x05 \x01(\x0c\x12\x14\n\x0csearch_label\x18\x06 \x01(\t\x12\x1c\n\x14system_resource_name\x18\x07 \x01(\t\x12\x1b\n\x13system_resource_num\x18\x08 \x01(\x12\">\n\x0cRenewalCount\x12\x1f\n\x17subscription_product_id\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x12\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'takasho.schema.fes.resource.subscription.renewal_reward.v1_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RENEWALREWARD._serialized_start=198
  _RENEWALREWARD._serialized_end=416
  _RENEWALREWARDPRIZE._serialized_start=419
  _RENEWALREWARDPRIZE._serialized_end=687
  _RENEWALCOUNT._serialized_start=689
  _RENEWALCOUNT._serialized_end=751
# @@protoc_insertion_point(module_scope)
