# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: takasho/schema/fes/resource/player_preference/v1.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6takasho/schema/fes/resource/player_preference/v1.proto\x12\x30takasho.schema.fes.resource.player_preference.v1\"Y\n\x10PlayerPreference\x12\x11\n\tplayer_id\x18\x01 \x01(\t\x12\x14\n\x0cplayer_level\x18\x02 \x01(\x04\x12\x1c\n\x14is_my_space_released\x18\x03 \x01(\x08\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'takasho.schema.fes.resource.player_preference.v1_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PLAYERPREFERENCE._serialized_start=108
  _PLAYERPREFERENCE._serialized_end=197
# @@protoc_insertion_point(module_scope)
