python -m grpc_tools.protoc -I. --python_out=.. --pyi_out=.. --grpc_python_out=.. takasho/schema/common_featureset/resource/ondemand_master/v2.proto
python -m grpc_tools.protoc -I. --python_out=.. --pyi_out=.. --grpc_python_out=.. takasho/schema/common_featureset/player_api/ondemand_master.proto
python -m grpc_tools.protoc -I. --python_out=.. --pyi_out=.. --grpc_python_out=.. takasho/schema/common_featureset/resource/system/v1.proto
python -m grpc_tools.protoc -I. --python_out=.. --pyi_out=.. --grpc_python_out=.. takasho/schema/common_featureset/resource/player_event_log/v1.proto
python -m grpc_tools.protoc -I. --python_out=.. --pyi_out=.. --grpc_python_out=.. takasho/schema/common_featureset/player_api/system.proto
python -m grpc_tools.protoc -I. --python_out=.. --pyi_out=.. --grpc_python_out=.. takasho/schema/fes/player_api/zendesk.proto
python -m grpc_tools.protoc -I. --python_out=.. --pyi_out=.. --grpc_python_out=.. takasho/schema/common_featureset/resource/player_preference/v1.proto
python -m grpc_tools.protoc -I. --python_out=.. --pyi_out=.. --grpc_python_out=.. takasho/schema/common_featureset/resource/player_storage/v2.proto
python -m grpc_tools.protoc -I. --python_out=.. --pyi_out=.. --grpc_python_out=.. takasho/schema/common_featureset/player_api/player_preference.proto
python -m grpc_tools.protoc -I. --python_out=.. --pyi_out=.. --grpc_python_out=.. takasho/schema/common_featureset/player_api/player_storage.proto
python -m grpc_tools.protoc -I. --python_out=.. --pyi_out=.. --grpc_python_out=.. takasho/schema/fes/resource/player_preference/v1.proto
python -m grpc_tools.protoc -I. --python_out=.. --pyi_out=.. --grpc_python_out=.. takasho/schema/fes/player_api/player_preference.proto
python -m grpc_tools.protoc -I. --python_out=.. --pyi_out=.. --grpc_python_out=.. takasho/schema/common_featureset/player_api/push_notification.proto
python -m grpc_tools.protoc -I. --python_out=.. --pyi_out=.. --grpc_python_out=.. takasho/schema/common_featureset/resource/game_status/v1.proto
python -m grpc_tools.protoc -I. --python_out=.. --pyi_out=.. --grpc_python_out=.. takasho/schema/common_featureset/player_api/game_status.proto
python -m grpc_tools.protoc -I. --python_out=.. --pyi_out=.. --grpc_python_out=.. takasho/schema/common_featureset/resource/consume_resource_set/v1.proto
python -m grpc_tools.protoc -I. --python_out=.. --pyi_out=.. --grpc_python_out=.. takasho/schema/common_featureset/resource/game_product/v1.proto
python -m grpc_tools.protoc -I. --python_out=.. --pyi_out=.. --grpc_python_out=.. takasho/schema/common_featureset/resource/player_inventory/v1.proto
python -m grpc_tools.protoc -I. --python_out=.. --pyi_out=.. --grpc_python_out=.. takasho/schema/common_featureset/resource/wallet/v3.proto
python -m grpc_tools.protoc -I. --python_out=.. --pyi_out=.. --grpc_python_out=.. takasho/schema/common_featureset/player_api/game_product.proto
python -m grpc_tools.protoc -I. --python_out=.. --pyi_out=.. --grpc_python_out=.. takasho/schema/common_featureset/player_api/wallet.proto
python -m grpc_tools.protoc -I. --python_out=.. --pyi_out=.. --grpc_python_out=.. takasho/schema/common_featureset/player_api/player_inventory.proto
python -m grpc_tools.protoc -I. --python_out=.. --pyi_out=.. --grpc_python_out=.. takasho/schema/fes/resource/friend/v1.proto
python -m grpc_tools.protoc -I. --python_out=.. --pyi_out=.. --grpc_python_out=.. takasho/schema/fes/player_api/friend.proto
python -m grpc_tools.protoc -I. --python_out=.. --pyi_out=.. --grpc_python_out=.. takasho/schema/fes/resource/score_ranking/v1.proto
python -m grpc_tools.protoc -I. --python_out=.. --pyi_out=.. --grpc_python_out=.. takasho/schema/fes/player_api/score_ranking.proto
python -m grpc_tools.protoc -I. --python_out=.. --pyi_out=.. --grpc_python_out=.. takasho/schema/common_featureset/resource/loot_box/v3.proto
python -m grpc_tools.protoc -I. --python_out=.. --pyi_out=.. --grpc_python_out=.. takasho/schema/common_featureset/player_api/loot_box.proto
python -m grpc_tools.protoc -I. --python_out=.. --pyi_out=.. --grpc_python_out=.. takasho/schema/common_featureset/resource/step_up_loot_box/v2.proto
python -m grpc_tools.protoc -I. --python_out=.. --pyi_out=.. --grpc_python_out=.. takasho/schema/common_featureset/resource/step_up_loot_box/v1.proto
python -m grpc_tools.protoc -I. --python_out=.. --pyi_out=.. --grpc_python_out=.. takasho/schema/common_featureset/player_api/step_up_loot_box.proto
python -m grpc_tools.protoc -I. --python_out=.. --pyi_out=.. --grpc_python_out=.. takasho/schema/fes/resource/club_storage/v1.proto
python -m grpc_tools.protoc -I. --python_out=.. --pyi_out=.. --grpc_python_out=.. takasho/schema/fes/resource/club_preference/v1.proto
python -m grpc_tools.protoc -I. --python_out=.. --pyi_out=.. --grpc_python_out=.. takasho/schema/fes/resource/club/v1.proto
python -m grpc_tools.protoc -I. --python_out=.. --pyi_out=.. --grpc_python_out=.. takasho/schema/fes/resource/club_role/v1.proto
python -m grpc_tools.protoc -I. --python_out=.. --pyi_out=.. --grpc_python_out=.. takasho/schema/fes/resource/club_player/v1.proto
python -m grpc_tools.protoc -I. --python_out=.. --pyi_out=.. --grpc_python_out=.. takasho/schema/fes/player_api/club_player.proto
python -m grpc_tools.protoc -I. --python_out=.. --pyi_out=.. --grpc_python_out=.. takasho/schema/common_featureset/resource/baas_product/v1.proto
python -m grpc_tools.protoc -I. --python_out=.. --pyi_out=.. --grpc_python_out=.. takasho/schema/common_featureset/player_api/baas_product.proto
python -m grpc_tools.protoc -I. --python_out=.. --pyi_out=.. --grpc_python_out=.. takasho/schema/fes/resource/subscription/renewal_reward/v1.proto
python -m grpc_tools.protoc -I. --python_out=.. --pyi_out=.. --grpc_python_out=.. takasho/schema/fes/player_api/subscription/renewal_reward.proto
python -m grpc_tools.protoc -I. --python_out=.. --pyi_out=.. --grpc_python_out=.. takasho/schema/fes/resource/reconstruction_spot/v1.proto
python -m grpc_tools.protoc -I. --python_out=.. --pyi_out=.. --grpc_python_out=.. takasho/schema/fes/player_api/reconstruction_spot.proto
python -m grpc_tools.protoc -I. --python_out=.. --pyi_out=.. --grpc_python_out=.. takasho/schema/fes/resource/login_bonus/v1.proto
python -m grpc_tools.protoc -I. --python_out=.. --pyi_out=.. --grpc_python_out=.. takasho/schema/common_featureset/resource/login_bonus/v1.proto
python -m grpc_tools.protoc -I. --python_out=.. --pyi_out=.. --grpc_python_out=.. takasho/schema/fes/resource/comeback_login_bonus/v1.proto
python -m grpc_tools.protoc -I. --python_out=.. --pyi_out=.. --grpc_python_out=.. takasho/schema/fes/player_api/login_bonus.proto
python -m grpc_tools.protoc -I. --python_out=.. --pyi_out=.. --grpc_python_out=.. takasho/schema/common_featureset/resource/achievement/v1.proto
python -m grpc_tools.protoc -I. --python_out=.. --pyi_out=.. --grpc_python_out=.. takasho/schema/common_featureset/resource/player_achievement/v1.proto
python -m grpc_tools.protoc -I. --python_out=.. --pyi_out=.. --grpc_python_out=.. takasho/schema/common_featureset/player_api/player_achievement.proto
python -m grpc_tools.protoc -I. --python_out=.. --pyi_out=.. --grpc_python_out=.. takasho/schema/common_featureset/resource/game_message/v1.proto
python -m grpc_tools.protoc -I. --python_out=.. --pyi_out=.. --grpc_python_out=.. takasho/schema/common_featureset/player_api/game_message.proto
python -m grpc_tools.protoc -I. --python_out=.. --pyi_out=.. --grpc_python_out=.. takasho/schema/common_featureset/resource/announcement/v1.proto
python -m grpc_tools.protoc -I. --python_out=.. --pyi_out=.. --grpc_python_out=.. takasho/schema/common_featureset/resource/extra_announcement/v1.proto
python -m grpc_tools.protoc -I. --python_out=.. --pyi_out=.. --grpc_python_out=.. takasho/schema/common_featureset/player_api/announcement.proto
python -m grpc_tools.protoc -I. --python_out=.. --pyi_out=.. --grpc_python_out=.. takasho/schema/fes/resource/club_chat/v1.proto
python -m grpc_tools.protoc -I. --python_out=.. --pyi_out=.. --grpc_python_out=.. takasho/schema/fes/player_api/club_chat.proto
python -m grpc_tools.protoc -I. --python_out=.. --pyi_out=.. --grpc_python_out=.. takasho/schema/fes/resource/club_achievement/v1.proto
python -m grpc_tools.protoc -I. --python_out=.. --pyi_out=.. --grpc_python_out=.. takasho/schema/fes/player_api/club_achievement.proto
python -m grpc_tools.protoc -I. --python_out=.. --pyi_out=.. --grpc_python_out=.. takasho/schema/common_featureset/player_api/player_event_log.proto
python -m grpc_tools.protoc -I. --python_out=.. --pyi_out=.. --grpc_python_out=.. takasho/schema/common_featureset/player_api/achievement.proto
python -m grpc_tools.protoc -I. --python_out=.. --pyi_out=.. --grpc_python_out=.. takasho/schema/fes/resource/player_regular_ranking/v1.proto
python -m grpc_tools.protoc -I. --python_out=.. --pyi_out=.. --grpc_python_out=.. takasho/schema/fes/player_api/regular_ranking.proto
python -m grpc_tools.protoc -I. --python_out=.. --pyi_out=.. --grpc_python_out=.. takasho/schema/common_featureset/resource/player_key_value/v1.proto
python -m grpc_tools.protoc -I. --python_out=.. --pyi_out=.. --grpc_python_out=.. takasho/schema/common_featureset/player_api/player_key_value_store.proto

python -m grpc_tools.protoc -I. --python_out=.. --pyi_out=.. --grpc_python_out=.. takasho/schema/fes/resource/player_event_log/v1.proto
