# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: takasho/schema/common_featureset/resource/extra_announcement/v1.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nEtakasho/schema/common_featureset/resource/extra_announcement/v1.proto\x12?takasho.schema.common_featureset.resource.extra_announcement.v1\"\xe7\x01\n\x11\x45xtraAnnouncement\x12\n\n\x02id\x18\x01 \x01(\t\x12\x15\n\rlanguage_code\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12\x11\n\topened_at\x18\x04 \x01(\x12\x12\x11\n\tclosed_at\x18\x05 \x01(\x12\x12\r\n\x05value\x18\x06 \x01(\x0c\x12k\n\x08\x63ontents\x18\x07 \x03(\x0b\x32Y.takasho.schema.common_featureset.resource.extra_announcement.v1.ExtraAnnouncementContent\"=\n\x18\x45xtraAnnouncementContent\x12\x12\n\nschema_key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'takasho.schema.common_featureset.resource.extra_announcement.v1_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EXTRAANNOUNCEMENT._serialized_start=139
  _EXTRAANNOUNCEMENT._serialized_end=370
  _EXTRAANNOUNCEMENTCONTENT._serialized_start=372
  _EXTRAANNOUNCEMENTCONTENT._serialized_end=433
# @@protoc_insertion_point(module_scope)
