# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: takasho/schema/fes/resource/club/v1.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from takasho.schema.fes.resource.club_preference import v1_pb2 as takasho_dot_schema_dot_fes_dot_resource_dot_club__preference_dot_v1__pb2
from takasho.schema.fes.resource.club_storage import v1_pb2 as takasho_dot_schema_dot_fes_dot_resource_dot_club__storage_dot_v1__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)takasho/schema/fes/resource/club/v1.proto\x12#takasho.schema.fes.resource.club.v1\x1a\x34takasho/schema/fes/resource/club_preference/v1.proto\x1a\x31takasho/schema/fes/resource/club_storage/v1.proto\"\xde\x01\n\x04\x43lub\x12\x0f\n\x07\x63lub_id\x18\x01 \x01(\t\x12\x14\n\x0corganized_at\x18\x02 \x01(\x12\x12R\n\npreference\x18\x03 \x01(\x0b\x32>.takasho.schema.fes.resource.club_preference.v1.ClubPreference\x12[\n\x14\x63lub_storage_entries\x18\x04 \x03(\x0b\x32=.takasho.schema.fes.resource.club_storage.v1.ClubStorageEntryb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'takasho.schema.fes.resource.club.v1_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CLUB._serialized_start=188
  _CLUB._serialized_end=410
# @@protoc_insertion_point(module_scope)
