# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: takasho/schema/fes/resource/club_achievement/v1.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5takasho/schema/fes/resource/club_achievement/v1.proto\x12/takasho.schema.fes.resource.club_achievement.v1\"\x8f\x02\n\x0f\x43lubAchievement\x12\x1b\n\x13\x63lub_achievement_id\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c\x12\x11\n\topened_at\x18\x03 \x01(\x12\x12\x11\n\tclosed_at\x18\x04 \x01(\x12\x12N\n\nreset_type\x18\x05 \x01(\x0e\x32:.takasho.schema.fes.resource.club_achievement.v1.ResetType\x12\x11\n\tdate_line\x18\x06 \x01(\t\x12\x13\n\x0b\x64\x61y_of_week\x18\x07 \x01(\x12\x12\x10\n\x08\x63\x61tegory\x18\x08 \x01(\t\x12\x0e\n\x06points\x18\t \x01(\x04\x12\x10\n\x08unlocked\x18\n \x01(\x08\"\x1c\n\x08\x43riteria\x12\x10\n\x08\x63\x61tegory\x18\x01 \x01(\t*3\n\tResetType\x12\x08\n\x04NONE\x10\x00\x12\r\n\tDATE_LINE\x10\x01\x12\r\n\tWEEK_LINE\x10\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'takasho.schema.fes.resource.club_achievement.v1_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RESETTYPE._serialized_start=410
  _RESETTYPE._serialized_end=461
  _CLUBACHIEVEMENT._serialized_start=107
  _CLUBACHIEVEMENT._serialized_end=378
  _CRITERIA._serialized_start=380
  _CRITERIA._serialized_end=408
# @@protoc_insertion_point(module_scope)
