# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: takasho/schema/fes/resource/club_chat/v1.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from takasho.schema.common_featureset.resource.player_storage import v2_pb2 as takasho_dot_schema_dot_common__featureset_dot_resource_dot_player__storage_dot_v2__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.takasho/schema/fes/resource/club_chat/v1.proto\x12(takasho.schema.fes.resource.club_chat.v1\x1a\x41takasho/schema/common_featureset/resource/player_storage/v2.proto\"\xf8\x01\n\x0f\x43lubChatMessage\x12\x0f\n\x07\x63lub_id\x18\x01 \x01(\t\x12\x12\n\nmessage_id\x18\x02 \x01(\t\x12K\n\x0cmessage_type\x18\x03 \x01(\x0e\x32\x35.takasho.schema.fes.resource.club_chat.v1.MessageType\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\t\x12O\n\x06player\x18\x05 \x01(\x0b\x32?.takasho.schema.fes.resource.club_chat.v1.ClubChatMessagePlayer\x12\x11\n\tposted_at\x18\x06 \x01(\x12\"\xa0\x01\n\x15\x43lubChatMessagePlayer\x12\x11\n\tplayer_id\x18\x01 \x01(\t\x12\x10\n\x08nickname\x18\x02 \x01(\t\x12\x62\n\x16player_storage_entries\x18\x03 \x03(\x0b\x32\x42.takasho.schema.common_featureset.resource.player_storage.v2.Entry*U\n\x0bMessageType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07\x43OMMENT\x10\x01\x12\x10\n\x0cNOTIFICATION\x10\x02\x12\x0f\n\x0b\x41\x43HIEVEMENT\x10\x03\x12\t\n\x05STAMP\x10\x04\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'takasho.schema.fes.resource.club_chat.v1_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGETYPE._serialized_start=573
  _MESSAGETYPE._serialized_end=658
  _CLUBCHATMESSAGE._serialized_start=160
  _CLUBCHATMESSAGE._serialized_end=408
  _CLUBCHATMESSAGEPLAYER._serialized_start=411
  _CLUBCHATMESSAGEPLAYER._serialized_end=571
# @@protoc_insertion_point(module_scope)
