# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: takasho/schema/fes/resource/reconstruction_spot/v1.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from takasho.schema.common_featureset.resource.player_inventory import v1_pb2 as takasho_dot_schema_dot_common__featureset_dot_resource_dot_player__inventory_dot_v1__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n8takasho/schema/fes/resource/reconstruction_spot/v1.proto\x12\x32takasho.schema.fes.resource.reconstruction_spot.v1\x1a\x43takasho/schema/common_featureset/resource/player_inventory/v1.proto\"\xaa\x01\n\x04Spot\x12\x0f\n\x07spot_id\x18\x01 \x01(\t\x12\x11\n\topened_at\x18\x02 \x01(\x04\x12\x13\n\x0b\x66inished_at\x18\x03 \x01(\x04\x12\x11\n\tclosed_at\x18\x04 \x01(\x04\x12\x0b\n\x03key\x18\x05 \x01(\t\x12I\n\x06stages\x18\x06 \x03(\x0b\x32\x39.takasho.schema.fes.resource.reconstruction_spot.v1.Stage\"\xc4\x01\n\x05Stage\x12\r\n\x05stage\x18\x01 \x01(\x04\x12\x19\n\x11max_tickets_count\x18\x02 \x01(\x04\x12\x11\n\topened_at\x18\x03 \x01(\x04\x12\x11\n\tclosed_at\x18\x04 \x01(\x04\x12I\n\x06prizes\x18\x05 \x03(\x0b\x32\x39.takasho.schema.fes.resource.reconstruction_spot.v1.Prize\x12 \n\x18\x61ggregated_tickets_count\x18\x06 \x01(\x04\"\xbc\x02\n\x05Prize\x12\x10\n\x08prize_id\x18\x01 \x01(\t\x12\r\n\x05ratio\x18\x02 \x01(\x02\x12Z\n\titem_type\x18\x03 \x01(\x0e\x32G.takasho.schema.common_featureset.resource.player_inventory.v1.ItemType\x12\x12\n\nschema_key\x18\x04 \x01(\t\x12\r\n\x05value\x18\x05 \x01(\x0c\x12\x12\n\nvalue_path\x18\x06 \x01(\t\x12\x19\n\x11inventory_message\x18\x07 \x01(\t\x12\x14\n\x0csearch_label\x18\x08 \x01(\t\x12\x1c\n\x14system_resource_name\x18\t \x01(\t\x12\x1b\n\x13system_resource_num\x18\n \x01(\x12\x12\x13\n\x0bis_unlocked\x18\x0b \x01(\x08\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'takasho.schema.fes.resource.reconstruction_spot.v1_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SPOT._serialized_start=182
  _SPOT._serialized_end=352
  _STAGE._serialized_start=355
  _STAGE._serialized_end=551
  _PRIZE._serialized_start=554
  _PRIZE._serialized_end=870
# @@protoc_insertion_point(module_scope)
