# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: takasho/schema/common_featureset/resource/game_product/v1.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from takasho.schema.common_featureset.resource.consume_resource_set import v1_pb2 as takasho_dot_schema_dot_common__featureset_dot_resource_dot_consume__resource__set_dot_v1__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n?takasho/schema/common_featureset/resource/game_product/v1.proto\x12\x39takasho.schema.common_featureset.resource.game_product.v1\x1aGtakasho/schema/common_featureset/resource/consume_resource_set/v1.proto\"\xbe\x02\n\x0bGameProduct\x12\x17\n\x0fgame_product_id\x18\x01 \x01(\t\x12\x12\n\nschema_key\x18\x06 \x01(\t\x12\r\n\x05value\x18\x07 \x01(\x0c\x12\x19\n\x11inventory_message\x18\x08 \x01(\t\x12\x11\n\topened_at\x18\t \x01(\x12\x12\x11\n\tclosed_at\x18\n \x01(\x12\x12\x16\n\x0ereceivable_sec\x18\x0b \x01(\x12\x12\x14\n\x0csearch_label\x18\x0c \x01(\t\x12t\n\x15\x63onsume_resource_sets\x18\r \x03(\x0b\x32U.takasho.schema.common_featureset.resource.consume_resource_set.v1.ConsumeResourceSet\x12\x0e\n\x06labels\x18\x0e \x03(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'takasho.schema.common_featureset.resource.game_product.v1_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GAMEPRODUCT._serialized_start=200
  _GAMEPRODUCT._serialized_end=518
# @@protoc_insertion_point(module_scope)
