# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from takasho.schema.fes.player_api import club_chat_pb2 as takasho_dot_schema_dot_fes_dot_player__api_dot_club__chat__pb2


class ClubChatStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateMessage = channel.unary_unary(
                '/takasho.schema.fes.player_api.club_chat.ClubChat/CreateMessage',
                request_serializer=takasho_dot_schema_dot_fes_dot_player__api_dot_club__chat__pb2.ClubChatCreateMessage.Request.SerializeToString,
                response_deserializer=takasho_dot_schema_dot_fes_dot_player__api_dot_club__chat__pb2.ClubChatCreateMessage.Response.FromString,
                )
        self.Get = channel.unary_unary(
                '/takasho.schema.fes.player_api.club_chat.ClubChat/Get',
                request_serializer=takasho_dot_schema_dot_fes_dot_player__api_dot_club__chat__pb2.ClubChatGet.Request.SerializeToString,
                response_deserializer=takasho_dot_schema_dot_fes_dot_player__api_dot_club__chat__pb2.ClubChatGet.Response.FromString,
                )
        self.GetMessagesCount = channel.unary_unary(
                '/takasho.schema.fes.player_api.club_chat.ClubChat/GetMessagesCount',
                request_serializer=takasho_dot_schema_dot_fes_dot_player__api_dot_club__chat__pb2.ClubChatGetMessagesCount.Request.SerializeToString,
                response_deserializer=takasho_dot_schema_dot_fes_dot_player__api_dot_club__chat__pb2.ClubChatGetMessagesCount.Response.FromString,
                )


class ClubChatServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMessagesCount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClubChatServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateMessage,
                    request_deserializer=takasho_dot_schema_dot_fes_dot_player__api_dot_club__chat__pb2.ClubChatCreateMessage.Request.FromString,
                    response_serializer=takasho_dot_schema_dot_fes_dot_player__api_dot_club__chat__pb2.ClubChatCreateMessage.Response.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=takasho_dot_schema_dot_fes_dot_player__api_dot_club__chat__pb2.ClubChatGet.Request.FromString,
                    response_serializer=takasho_dot_schema_dot_fes_dot_player__api_dot_club__chat__pb2.ClubChatGet.Response.SerializeToString,
            ),
            'GetMessagesCount': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMessagesCount,
                    request_deserializer=takasho_dot_schema_dot_fes_dot_player__api_dot_club__chat__pb2.ClubChatGetMessagesCount.Request.FromString,
                    response_serializer=takasho_dot_schema_dot_fes_dot_player__api_dot_club__chat__pb2.ClubChatGetMessagesCount.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'takasho.schema.fes.player_api.club_chat.ClubChat', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ClubChat(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/takasho.schema.fes.player_api.club_chat.ClubChat/CreateMessage',
            takasho_dot_schema_dot_fes_dot_player__api_dot_club__chat__pb2.ClubChatCreateMessage.Request.SerializeToString,
            takasho_dot_schema_dot_fes_dot_player__api_dot_club__chat__pb2.ClubChatCreateMessage.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/takasho.schema.fes.player_api.club_chat.ClubChat/Get',
            takasho_dot_schema_dot_fes_dot_player__api_dot_club__chat__pb2.ClubChatGet.Request.SerializeToString,
            takasho_dot_schema_dot_fes_dot_player__api_dot_club__chat__pb2.ClubChatGet.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMessagesCount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/takasho.schema.fes.player_api.club_chat.ClubChat/GetMessagesCount',
            takasho_dot_schema_dot_fes_dot_player__api_dot_club__chat__pb2.ClubChatGetMessagesCount.Request.SerializeToString,
            takasho_dot_schema_dot_fes_dot_player__api_dot_club__chat__pb2.ClubChatGetMessagesCount.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
