# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: takasho/schema/fes/player_api/club_achievement.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from takasho.schema.fes.resource.club_achievement import v1_pb2 as takasho_dot_schema_dot_fes_dot_resource_dot_club__achievement_dot_v1__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n4takasho/schema/fes/player_api/club_achievement.proto\x12.takasho.schema.fes.player_api.club_achievement\x1a\x35takasho/schema/fes/resource/club_achievement/v1.proto\"\x9b\x02\n\x1b\x43lubAchievementGetAvailable\x1a\x7f\n\x07Request\x12K\n\x08\x63riteria\x18\x01 \x01(\x0b\x32\x39.takasho.schema.fes.resource.club_achievement.v1.Criteria\x12\x12\n\npage_token\x18\x02 \x01(\t\x12\x13\n\x0bmax_results\x18\x03 \x01(\x04\x1a{\n\x08Response\x12V\n\x0c\x61\x63hievements\x18\x01 \x03(\x0b\x32@.takasho.schema.fes.resource.club_achievement.v1.ClubAchievement\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\"p\n+ClubAchievementUnlockAndIncrementClubScalar\x1a\x35\n\x07Request\x12\x16\n\x0e\x61\x63hievement_id\x18\x01 \x01(\t\x12\x12\n\nscalar_key\x18\x02 \x01(\t\x1a\n\n\x08Response2\xbd\x03\n\x0f\x43lubAchievement\x12\xbb\x01\n\x0cGetAvailable\x12S.takasho.schema.fes.player_api.club_achievement.ClubAchievementGetAvailable.Request\x1aT.takasho.schema.fes.player_api.club_achievement.ClubAchievementGetAvailable.Response\"\x00\x12\xeb\x01\n\x1cUnlockAndIncrementClubScalar\x12\x63.takasho.schema.fes.player_api.club_achievement.ClubAchievementUnlockAndIncrementClubScalar.Request\x1a\x64.takasho.schema.fes.player_api.club_achievement.ClubAchievementUnlockAndIncrementClubScalar.Response\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'takasho.schema.fes.player_api.club_achievement_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CLUBACHIEVEMENTGETAVAILABLE._serialized_start=160
  _CLUBACHIEVEMENTGETAVAILABLE._serialized_end=443
  _CLUBACHIEVEMENTGETAVAILABLE_REQUEST._serialized_start=191
  _CLUBACHIEVEMENTGETAVAILABLE_REQUEST._serialized_end=318
  _CLUBACHIEVEMENTGETAVAILABLE_RESPONSE._serialized_start=320
  _CLUBACHIEVEMENTGETAVAILABLE_RESPONSE._serialized_end=443
  _CLUBACHIEVEMENTUNLOCKANDINCREMENTCLUBSCALAR._serialized_start=445
  _CLUBACHIEVEMENTUNLOCKANDINCREMENTCLUBSCALAR._serialized_end=557
  _CLUBACHIEVEMENTUNLOCKANDINCREMENTCLUBSCALAR_REQUEST._serialized_start=492
  _CLUBACHIEVEMENTUNLOCKANDINCREMENTCLUBSCALAR_REQUEST._serialized_end=545
  _CLUBACHIEVEMENTUNLOCKANDINCREMENTCLUBSCALAR_RESPONSE._serialized_start=320
  _CLUBACHIEVEMENTUNLOCKANDINCREMENTCLUBSCALAR_RESPONSE._serialized_end=330
  _CLUBACHIEVEMENT._serialized_start=560
  _CLUBACHIEVEMENT._serialized_end=1005
# @@protoc_insertion_point(module_scope)
