# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from takasho.schema.fes.player_api import friend_pb2 as takasho_dot_schema_dot_fes_dot_player__api_dot_friend__pb2


class FriendStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FollowV1 = channel.unary_unary(
                '/takasho.schema.fes.player_api.friend.Friend/FollowV1',
                request_serializer=takasho_dot_schema_dot_fes_dot_player__api_dot_friend__pb2.FriendFollowV1.Request.SerializeToString,
                response_deserializer=takasho_dot_schema_dot_fes_dot_player__api_dot_friend__pb2.FriendFollowV1.Response.FromString,
                )
        self.UnfollowV1 = channel.unary_unary(
                '/takasho.schema.fes.player_api.friend.Friend/UnfollowV1',
                request_serializer=takasho_dot_schema_dot_fes_dot_player__api_dot_friend__pb2.FriendUnfollowV1.Request.SerializeToString,
                response_deserializer=takasho_dot_schema_dot_fes_dot_player__api_dot_friend__pb2.FriendUnfollowV1.Response.FromString,
                )
        self.RemoveMyFollowerV1 = channel.unary_unary(
                '/takasho.schema.fes.player_api.friend.Friend/RemoveMyFollowerV1',
                request_serializer=takasho_dot_schema_dot_fes_dot_player__api_dot_friend__pb2.FriendRemoveMyFollowerV1.Request.SerializeToString,
                response_deserializer=takasho_dot_schema_dot_fes_dot_player__api_dot_friend__pb2.FriendRemoveMyFollowerV1.Response.FromString,
                )
        self.SearchPlayerByPlayerShortIDV1 = channel.unary_unary(
                '/takasho.schema.fes.player_api.friend.Friend/SearchPlayerByPlayerShortIDV1',
                request_serializer=takasho_dot_schema_dot_fes_dot_player__api_dot_friend__pb2.FriendSearchPlayerByPlayerShortIDV1.Request.SerializeToString,
                response_deserializer=takasho_dot_schema_dot_fes_dot_player__api_dot_friend__pb2.FriendSearchPlayerByPlayerShortIDV1.Response.FromString,
                )
        self.GetMyFollowersV1 = channel.unary_unary(
                '/takasho.schema.fes.player_api.friend.Friend/GetMyFollowersV1',
                request_serializer=takasho_dot_schema_dot_fes_dot_player__api_dot_friend__pb2.FriendGetMyFollowersV1.Request.SerializeToString,
                response_deserializer=takasho_dot_schema_dot_fes_dot_player__api_dot_friend__pb2.FriendGetMyFollowersV1.Response.FromString,
                )
        self.GetMyFollowingsV1 = channel.unary_unary(
                '/takasho.schema.fes.player_api.friend.Friend/GetMyFollowingsV1',
                request_serializer=takasho_dot_schema_dot_fes_dot_player__api_dot_friend__pb2.FriendGetMyFollowingsV1.Request.SerializeToString,
                response_deserializer=takasho_dot_schema_dot_fes_dot_player__api_dot_friend__pb2.FriendGetMyFollowingsV1.Response.FromString,
                )
        self.GetRecentlyLoggedInPlayersV1 = channel.unary_unary(
                '/takasho.schema.fes.player_api.friend.Friend/GetRecentlyLoggedInPlayersV1',
                request_serializer=takasho_dot_schema_dot_fes_dot_player__api_dot_friend__pb2.FriendGetRecentlyLoggedInPlayersV1.Request.SerializeToString,
                response_deserializer=takasho_dot_schema_dot_fes_dot_player__api_dot_friend__pb2.FriendGetRecentlyLoggedInPlayersV1.Response.FromString,
                )
        self.GetFollowStatusesV1 = channel.unary_unary(
                '/takasho.schema.fes.player_api.friend.Friend/GetFollowStatusesV1',
                request_serializer=takasho_dot_schema_dot_fes_dot_player__api_dot_friend__pb2.FriendGetFollowStatusesV1.Request.SerializeToString,
                response_deserializer=takasho_dot_schema_dot_fes_dot_player__api_dot_friend__pb2.FriendGetFollowStatusesV1.Response.FromString,
                )


class FriendServicer(object):
    """Missing associated documentation comment in .proto file."""

    def FollowV1(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnfollowV1(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveMyFollowerV1(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchPlayerByPlayerShortIDV1(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMyFollowersV1(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMyFollowingsV1(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRecentlyLoggedInPlayersV1(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFollowStatusesV1(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FriendServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FollowV1': grpc.unary_unary_rpc_method_handler(
                    servicer.FollowV1,
                    request_deserializer=takasho_dot_schema_dot_fes_dot_player__api_dot_friend__pb2.FriendFollowV1.Request.FromString,
                    response_serializer=takasho_dot_schema_dot_fes_dot_player__api_dot_friend__pb2.FriendFollowV1.Response.SerializeToString,
            ),
            'UnfollowV1': grpc.unary_unary_rpc_method_handler(
                    servicer.UnfollowV1,
                    request_deserializer=takasho_dot_schema_dot_fes_dot_player__api_dot_friend__pb2.FriendUnfollowV1.Request.FromString,
                    response_serializer=takasho_dot_schema_dot_fes_dot_player__api_dot_friend__pb2.FriendUnfollowV1.Response.SerializeToString,
            ),
            'RemoveMyFollowerV1': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveMyFollowerV1,
                    request_deserializer=takasho_dot_schema_dot_fes_dot_player__api_dot_friend__pb2.FriendRemoveMyFollowerV1.Request.FromString,
                    response_serializer=takasho_dot_schema_dot_fes_dot_player__api_dot_friend__pb2.FriendRemoveMyFollowerV1.Response.SerializeToString,
            ),
            'SearchPlayerByPlayerShortIDV1': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchPlayerByPlayerShortIDV1,
                    request_deserializer=takasho_dot_schema_dot_fes_dot_player__api_dot_friend__pb2.FriendSearchPlayerByPlayerShortIDV1.Request.FromString,
                    response_serializer=takasho_dot_schema_dot_fes_dot_player__api_dot_friend__pb2.FriendSearchPlayerByPlayerShortIDV1.Response.SerializeToString,
            ),
            'GetMyFollowersV1': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMyFollowersV1,
                    request_deserializer=takasho_dot_schema_dot_fes_dot_player__api_dot_friend__pb2.FriendGetMyFollowersV1.Request.FromString,
                    response_serializer=takasho_dot_schema_dot_fes_dot_player__api_dot_friend__pb2.FriendGetMyFollowersV1.Response.SerializeToString,
            ),
            'GetMyFollowingsV1': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMyFollowingsV1,
                    request_deserializer=takasho_dot_schema_dot_fes_dot_player__api_dot_friend__pb2.FriendGetMyFollowingsV1.Request.FromString,
                    response_serializer=takasho_dot_schema_dot_fes_dot_player__api_dot_friend__pb2.FriendGetMyFollowingsV1.Response.SerializeToString,
            ),
            'GetRecentlyLoggedInPlayersV1': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRecentlyLoggedInPlayersV1,
                    request_deserializer=takasho_dot_schema_dot_fes_dot_player__api_dot_friend__pb2.FriendGetRecentlyLoggedInPlayersV1.Request.FromString,
                    response_serializer=takasho_dot_schema_dot_fes_dot_player__api_dot_friend__pb2.FriendGetRecentlyLoggedInPlayersV1.Response.SerializeToString,
            ),
            'GetFollowStatusesV1': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFollowStatusesV1,
                    request_deserializer=takasho_dot_schema_dot_fes_dot_player__api_dot_friend__pb2.FriendGetFollowStatusesV1.Request.FromString,
                    response_serializer=takasho_dot_schema_dot_fes_dot_player__api_dot_friend__pb2.FriendGetFollowStatusesV1.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'takasho.schema.fes.player_api.friend.Friend', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Friend(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def FollowV1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/takasho.schema.fes.player_api.friend.Friend/FollowV1',
            takasho_dot_schema_dot_fes_dot_player__api_dot_friend__pb2.FriendFollowV1.Request.SerializeToString,
            takasho_dot_schema_dot_fes_dot_player__api_dot_friend__pb2.FriendFollowV1.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UnfollowV1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/takasho.schema.fes.player_api.friend.Friend/UnfollowV1',
            takasho_dot_schema_dot_fes_dot_player__api_dot_friend__pb2.FriendUnfollowV1.Request.SerializeToString,
            takasho_dot_schema_dot_fes_dot_player__api_dot_friend__pb2.FriendUnfollowV1.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemoveMyFollowerV1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/takasho.schema.fes.player_api.friend.Friend/RemoveMyFollowerV1',
            takasho_dot_schema_dot_fes_dot_player__api_dot_friend__pb2.FriendRemoveMyFollowerV1.Request.SerializeToString,
            takasho_dot_schema_dot_fes_dot_player__api_dot_friend__pb2.FriendRemoveMyFollowerV1.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SearchPlayerByPlayerShortIDV1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/takasho.schema.fes.player_api.friend.Friend/SearchPlayerByPlayerShortIDV1',
            takasho_dot_schema_dot_fes_dot_player__api_dot_friend__pb2.FriendSearchPlayerByPlayerShortIDV1.Request.SerializeToString,
            takasho_dot_schema_dot_fes_dot_player__api_dot_friend__pb2.FriendSearchPlayerByPlayerShortIDV1.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMyFollowersV1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/takasho.schema.fes.player_api.friend.Friend/GetMyFollowersV1',
            takasho_dot_schema_dot_fes_dot_player__api_dot_friend__pb2.FriendGetMyFollowersV1.Request.SerializeToString,
            takasho_dot_schema_dot_fes_dot_player__api_dot_friend__pb2.FriendGetMyFollowersV1.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMyFollowingsV1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/takasho.schema.fes.player_api.friend.Friend/GetMyFollowingsV1',
            takasho_dot_schema_dot_fes_dot_player__api_dot_friend__pb2.FriendGetMyFollowingsV1.Request.SerializeToString,
            takasho_dot_schema_dot_fes_dot_player__api_dot_friend__pb2.FriendGetMyFollowingsV1.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRecentlyLoggedInPlayersV1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/takasho.schema.fes.player_api.friend.Friend/GetRecentlyLoggedInPlayersV1',
            takasho_dot_schema_dot_fes_dot_player__api_dot_friend__pb2.FriendGetRecentlyLoggedInPlayersV1.Request.SerializeToString,
            takasho_dot_schema_dot_fes_dot_player__api_dot_friend__pb2.FriendGetRecentlyLoggedInPlayersV1.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetFollowStatusesV1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/takasho.schema.fes.player_api.friend.Friend/GetFollowStatusesV1',
            takasho_dot_schema_dot_fes_dot_player__api_dot_friend__pb2.FriendGetFollowStatusesV1.Request.SerializeToString,
            takasho_dot_schema_dot_fes_dot_player__api_dot_friend__pb2.FriendGetFollowStatusesV1.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
