# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from takasho.schema.fes.player_api import player_preference_pb2 as takasho_dot_schema_dot_fes_dot_player__api_dot_player__preference__pb2


class FesPlayerPreferenceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetV1 = channel.unary_unary(
                '/takasho.schema.fes.player_api.player_preference.FesPlayerPreference/GetV1',
                request_serializer=takasho_dot_schema_dot_fes_dot_player__api_dot_player__preference__pb2.FesPlayerPreferenceGetV1.Request.SerializeToString,
                response_deserializer=takasho_dot_schema_dot_fes_dot_player__api_dot_player__preference__pb2.FesPlayerPreferenceGetV1.Response.FromString,
                )
        self.SetAndSavePlayerStorageV1 = channel.unary_unary(
                '/takasho.schema.fes.player_api.player_preference.FesPlayerPreference/SetAndSavePlayerStorageV1',
                request_serializer=takasho_dot_schema_dot_fes_dot_player__api_dot_player__preference__pb2.FesPlayerPreferenceSetAndSavePlayerStorageV1.Request.SerializeToString,
                response_deserializer=takasho_dot_schema_dot_fes_dot_player__api_dot_player__preference__pb2.FesPlayerPreferenceSetAndSavePlayerStorageV1.Response.FromString,
                )


class FesPlayerPreferenceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetV1(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetAndSavePlayerStorageV1(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FesPlayerPreferenceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetV1': grpc.unary_unary_rpc_method_handler(
                    servicer.GetV1,
                    request_deserializer=takasho_dot_schema_dot_fes_dot_player__api_dot_player__preference__pb2.FesPlayerPreferenceGetV1.Request.FromString,
                    response_serializer=takasho_dot_schema_dot_fes_dot_player__api_dot_player__preference__pb2.FesPlayerPreferenceGetV1.Response.SerializeToString,
            ),
            'SetAndSavePlayerStorageV1': grpc.unary_unary_rpc_method_handler(
                    servicer.SetAndSavePlayerStorageV1,
                    request_deserializer=takasho_dot_schema_dot_fes_dot_player__api_dot_player__preference__pb2.FesPlayerPreferenceSetAndSavePlayerStorageV1.Request.FromString,
                    response_serializer=takasho_dot_schema_dot_fes_dot_player__api_dot_player__preference__pb2.FesPlayerPreferenceSetAndSavePlayerStorageV1.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'takasho.schema.fes.player_api.player_preference.FesPlayerPreference', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FesPlayerPreference(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetV1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/takasho.schema.fes.player_api.player_preference.FesPlayerPreference/GetV1',
            takasho_dot_schema_dot_fes_dot_player__api_dot_player__preference__pb2.FesPlayerPreferenceGetV1.Request.SerializeToString,
            takasho_dot_schema_dot_fes_dot_player__api_dot_player__preference__pb2.FesPlayerPreferenceGetV1.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetAndSavePlayerStorageV1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/takasho.schema.fes.player_api.player_preference.FesPlayerPreference/SetAndSavePlayerStorageV1',
            takasho_dot_schema_dot_fes_dot_player__api_dot_player__preference__pb2.FesPlayerPreferenceSetAndSavePlayerStorageV1.Request.SerializeToString,
            takasho_dot_schema_dot_fes_dot_player__api_dot_player__preference__pb2.FesPlayerPreferenceSetAndSavePlayerStorageV1.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
