# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: takasho/schema/fes/player_api/player_preference.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from takasho.schema.fes.resource.player_preference import v1_pb2 as takasho_dot_schema_dot_fes_dot_resource_dot_player__preference_dot_v1__pb2
from takasho.schema.common_featureset.resource.player_storage import v2_pb2 as takasho_dot_schema_dot_common__featureset_dot_resource_dot_player__storage_dot_v2__pb2
from takasho.schema.common_featureset.resource.player_event_log import v1_pb2 as takasho_dot_schema_dot_common__featureset_dot_resource_dot_player__event__log_dot_v1__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5takasho/schema/fes/player_api/player_preference.proto\x12/takasho.schema.fes.player_api.player_preference\x1a\x36takasho/schema/fes/resource/player_preference/v1.proto\x1a\x41takasho/schema/common_featureset/resource/player_storage/v2.proto\x1a\x43takasho/schema/common_featureset/resource/player_event_log/v1.proto\"\x90\x01\n\x18\x46\x65sPlayerPreferenceGetV1\x1a\t\n\x07Request\x1ai\n\x08Response\x12]\n\x11player_preference\x18\x01 \x01(\x0b\x32\x42.takasho.schema.fes.resource.player_preference.v1.PlayerPreference\"\xdd\x04\n,FesPlayerPreferenceSetAndSavePlayerStorageV1\x1a\xd9\x02\n\x07Request\x12]\n\x11player_preference\x18\x01 \x01(\x0b\x32\x42.takasho.schema.fes.resource.player_preference.v1.PlayerPreference\x12S\n\x07\x65ntries\x18\x02 \x03(\x0b\x32\x42.takasho.schema.common_featureset.resource.player_storage.v2.Entry\x12\x15\n\rnext_revision\x18\x03 \x01(\t\x12\x19\n\x11previous_revision\x18\x04 \x01(\t\x12h\n\x11player_event_logs\x18\x05 \x03(\x0b\x32M.takasho.schema.common_featureset.resource.player_event_log.v1.PlayerEventLog\x1a\xd0\x01\n\x08Response\x12]\n\x11player_preference\x18\x01 \x01(\x0b\x32\x42.takasho.schema.fes.resource.player_preference.v1.PlayerPreference\x12S\n\x07\x65ntries\x18\x02 \x03(\x0b\x32\x42.takasho.schema.common_featureset.resource.player_storage.v2.Entry\x12\x10\n\x08revision\x18\x03 \x01(\t2\xb7\x03\n\x13\x46\x65sPlayerPreference\x12\xb0\x01\n\x05GetV1\x12Q.takasho.schema.fes.player_api.player_preference.FesPlayerPreferenceGetV1.Request\x1aR.takasho.schema.fes.player_api.player_preference.FesPlayerPreferenceGetV1.Response\"\x00\x12\xec\x01\n\x19SetAndSavePlayerStorageV1\x12\x65.takasho.schema.fes.player_api.player_preference.FesPlayerPreferenceSetAndSavePlayerStorageV1.Request\x1a\x66.takasho.schema.fes.player_api.player_preference.FesPlayerPreferenceSetAndSavePlayerStorageV1.Response\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'takasho.schema.fes.player_api.player_preference_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FESPLAYERPREFERENCEGETV1._serialized_start=299
  _FESPLAYERPREFERENCEGETV1._serialized_end=443
  _FESPLAYERPREFERENCEGETV1_REQUEST._serialized_start=327
  _FESPLAYERPREFERENCEGETV1_REQUEST._serialized_end=336
  _FESPLAYERPREFERENCEGETV1_RESPONSE._serialized_start=338
  _FESPLAYERPREFERENCEGETV1_RESPONSE._serialized_end=443
  _FESPLAYERPREFERENCESETANDSAVEPLAYERSTORAGEV1._serialized_start=446
  _FESPLAYERPREFERENCESETANDSAVEPLAYERSTORAGEV1._serialized_end=1051
  _FESPLAYERPREFERENCESETANDSAVEPLAYERSTORAGEV1_REQUEST._serialized_start=495
  _FESPLAYERPREFERENCESETANDSAVEPLAYERSTORAGEV1_REQUEST._serialized_end=840
  _FESPLAYERPREFERENCESETANDSAVEPLAYERSTORAGEV1_RESPONSE._serialized_start=843
  _FESPLAYERPREFERENCESETANDSAVEPLAYERSTORAGEV1_RESPONSE._serialized_end=1051
  _FESPLAYERPREFERENCE._serialized_start=1054
  _FESPLAYERPREFERENCE._serialized_end=1493
# @@protoc_insertion_point(module_scope)
