# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from takasho.schema.fes.player_api import regular_ranking_pb2 as takasho_dot_schema_dot_fes_dot_player__api_dot_regular__ranking__pb2


class RegularRankingStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterV1 = channel.unary_unary(
                '/takasho.schema.fes.player_api.RegularRanking/RegisterV1',
                request_serializer=takasho_dot_schema_dot_fes_dot_player__api_dot_regular__ranking__pb2.RegularRankingRegisterV1.Request.SerializeToString,
                response_deserializer=takasho_dot_schema_dot_fes_dot_player__api_dot_regular__ranking__pb2.RegularRankingRegisterV1.Response.FromString,
                )
        self.GetTopRankingV1 = channel.unary_unary(
                '/takasho.schema.fes.player_api.RegularRanking/GetTopRankingV1',
                request_serializer=takasho_dot_schema_dot_fes_dot_player__api_dot_regular__ranking__pb2.RegularRankingGetTopRankingV1.Request.SerializeToString,
                response_deserializer=takasho_dot_schema_dot_fes_dot_player__api_dot_regular__ranking__pb2.RegularRankingGetTopRankingV1.Response.FromString,
                )


class RegularRankingServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterV1(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTopRankingV1(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RegularRankingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterV1': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterV1,
                    request_deserializer=takasho_dot_schema_dot_fes_dot_player__api_dot_regular__ranking__pb2.RegularRankingRegisterV1.Request.FromString,
                    response_serializer=takasho_dot_schema_dot_fes_dot_player__api_dot_regular__ranking__pb2.RegularRankingRegisterV1.Response.SerializeToString,
            ),
            'GetTopRankingV1': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTopRankingV1,
                    request_deserializer=takasho_dot_schema_dot_fes_dot_player__api_dot_regular__ranking__pb2.RegularRankingGetTopRankingV1.Request.FromString,
                    response_serializer=takasho_dot_schema_dot_fes_dot_player__api_dot_regular__ranking__pb2.RegularRankingGetTopRankingV1.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'takasho.schema.fes.player_api.RegularRanking', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RegularRanking(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterV1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/takasho.schema.fes.player_api.RegularRanking/RegisterV1',
            takasho_dot_schema_dot_fes_dot_player__api_dot_regular__ranking__pb2.RegularRankingRegisterV1.Request.SerializeToString,
            takasho_dot_schema_dot_fes_dot_player__api_dot_regular__ranking__pb2.RegularRankingRegisterV1.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTopRankingV1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/takasho.schema.fes.player_api.RegularRanking/GetTopRankingV1',
            takasho_dot_schema_dot_fes_dot_player__api_dot_regular__ranking__pb2.RegularRankingGetTopRankingV1.Request.SerializeToString,
            takasho_dot_schema_dot_fes_dot_player__api_dot_regular__ranking__pb2.RegularRankingGetTopRankingV1.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
