# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: takasho/schema/fes/player_api/zendesk.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+takasho/schema/fes/player_api/zendesk.proto\x12\x1dtakasho.schema.fes.player_api\"F\n\x17ZendeskGetUnreadCountV1\x1a\t\n\x07Request\x1a \n\x08Response\x12\x14\n\x0cunread_count\x18\x01 \x01(\x03\x32\xa1\x01\n\x07Zendesk\x12\x95\x01\n\x10GetUnreadCountV1\x12>.takasho.schema.fes.player_api.ZendeskGetUnreadCountV1.Request\x1a?.takasho.schema.fes.player_api.ZendeskGetUnreadCountV1.Response\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'takasho.schema.fes.player_api.zendesk_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ZENDESKGETUNREADCOUNTV1._serialized_start=78
  _ZENDESKGETUNREADCOUNTV1._serialized_end=148
  _ZENDESKGETUNREADCOUNTV1_REQUEST._serialized_start=105
  _ZENDESKGETUNREADCOUNTV1_REQUEST._serialized_end=114
  _ZENDESKGETUNREADCOUNTV1_RESPONSE._serialized_start=116
  _ZENDESKGETUNREADCOUNTV1_RESPONSE._serialized_end=148
  _ZENDESK._serialized_start=151
  _ZENDESK._serialized_end=312
# @@protoc_insertion_point(module_scope)
