# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: takasho/schema/fes/resource/comeback_login_bonus/v1.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from takasho.schema.common_featureset.resource.login_bonus import v1_pb2 as takasho_dot_schema_dot_common__featureset_dot_resource_dot_login__bonus_dot_v1__pb2
from takasho.schema.common_featureset.resource.player_inventory import v1_pb2 as takasho_dot_schema_dot_common__featureset_dot_resource_dot_player__inventory_dot_v1__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n9takasho/schema/fes/resource/comeback_login_bonus/v1.proto\x12\x33takasho.schema.fes.resource.comeback_login_bonus.v1\x1a>takasho/schema/common_featureset/resource/login_bonus/v1.proto\x1a\x43takasho/schema/common_featureset/resource/player_inventory/v1.proto\"\x96\x03\n\x12\x43omebackLoginBonus\x12\x1f\n\x17\x63omeback_login_bonus_id\x18\x01 \x01(\t\x12\x11\n\topened_at\x18\x02 \x01(\x12\x12\x11\n\tclosed_at\x18\x03 \x01(\x12\x12\x16\n\x0e\x63ondition_days\x18\x04 \x01(\x12\x12\x12\n\nvalid_days\x18\x05 \x01(\x12\x12W\n\nreset_type\x18\x06 \x01(\x0e\x32\x43.takasho.schema.common_featureset.resource.login_bonus.v1.ResetType\x12\x11\n\tdate_line\x18\x07 \x01(\t\x12\x12\n\ntime_lapse\x18\x08 \x01(\x12\x12q\n\x1b\x63omeback_login_bonus_prizes\x18\t \x03(\x0b\x32L.takasho.schema.fes.resource.comeback_login_bonus.v1.ComebackLoginBonusPrize\x12\x1a\n\x12last_counted_up_at\x18\n \x01(\x12\"\xa6\x02\n\x17\x43omebackLoginBonusPrize\x12\x0c\n\x04\x64\x61ys\x18\x01 \x01(\x12\x12Z\n\titem_type\x18\x02 \x01(\x0e\x32G.takasho.schema.common_featureset.resource.player_inventory.v1.ItemType\x12\x12\n\nschema_key\x18\x03 \x01(\t\x12\r\n\x05value\x18\x04 \x01(\t\x12\x12\n\nvalue_path\x18\x05 \x01(\t\x12\x19\n\x11inventory_message\x18\x06 \x01(\t\x12\x14\n\x0csearch_label\x18\x07 \x01(\t\x12\x1c\n\x14system_resource_name\x18\x08 \x01(\t\x12\x1b\n\x13system_resource_num\x18\t \x01(\x03\"p\n\x1a\x43omebackLoginBonusProgress\x12\x11\n\tplayer_id\x18\x01 \x01(\t\x12\x13\n\x0bremain_days\x18\x02 \x01(\x12\x12\x16\n\x0e\x63ome_backed_at\x18\x03 \x01(\x12\x12\x12\n\nexpired_at\x18\x04 \x01(\x12\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'takasho.schema.fes.resource.comeback_login_bonus.v1_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COMEBACKLOGINBONUS._serialized_start=248
  _COMEBACKLOGINBONUS._serialized_end=654
  _COMEBACKLOGINBONUSPRIZE._serialized_start=657
  _COMEBACKLOGINBONUSPRIZE._serialized_end=951
  _COMEBACKLOGINBONUSPROGRESS._serialized_start=953
  _COMEBACKLOGINBONUSPROGRESS._serialized_end=1065
# @@protoc_insertion_point(module_scope)
