# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: takasho/schema/common_featureset/resource/player_key_value/v1.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nCtakasho/schema/common_featureset/resource/player_key_value/v1.proto\x12=takasho.schema.common_featureset.resource.player_key_value.v1\"@\n\x0ePlayerKeyValue\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x12\x12\x12\n\nexpired_at\x18\x03 \x01(\x12\"9\n\x1bPlayerKeyValueIncrementInfo\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05\x64\x65lta\x18\x02 \x01(\x12\"7\n\x18PlayerKeyValueUpdateInfo\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x12*8\n\rOperationType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0c\n\x08INCREASE\x10\x01\x12\x0c\n\x08\x44\x45\x43REASE\x10\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'takasho.schema.common_featureset.resource.player_key_value.v1_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _OPERATIONTYPE._serialized_start=316
  _OPERATIONTYPE._serialized_end=372
  _PLAYERKEYVALUE._serialized_start=134
  _PLAYERKEYVALUE._serialized_end=198
  _PLAYERKEYVALUEINCREMENTINFO._serialized_start=200
  _PLAYERKEYVALUEINCREMENTINFO._serialized_end=257
  _PLAYERKEYVALUEUPDATEINFO._serialized_start=259
  _PLAYERKEYVALUEUPDATEINFO._serialized_end=314
# @@protoc_insertion_point(module_scope)
