# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: takasho/schema/common_featureset/resource/baas_product/v1.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from takasho.schema.common_featureset.resource.player_inventory import v1_pb2 as takasho_dot_schema_dot_common__featureset_dot_resource_dot_player__inventory_dot_v1__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n?takasho/schema/common_featureset/resource/baas_product/v1.proto\x12\x39takasho.schema.common_featureset.resource.baas_product.v1\x1a\x43takasho/schema/common_featureset/resource/player_inventory/v1.proto\"\x9e\x01\n\x0b\x42\x61\x61sProduct\x12\x17\n\x0f\x62\x61\x61s_product_id\x18\x01 \x01(\t\x12\x19\n\x11inventory_message\x18\x02 \x01(\t\x12[\n\x06\x65xtras\x18\x03 \x03(\x0b\x32K.takasho.schema.common_featureset.resource.baas_product.v1.BaasProductExtra\"\x81\x02\n\x10\x42\x61\x61sProductExtra\x12\x1d\n\x15\x62\x61\x61s_product_extra_id\x18\x01 \x01(\t\x12Z\n\titem_type\x18\x02 \x01(\x0e\x32G.takasho.schema.common_featureset.resource.player_inventory.v1.ItemType\x12\x12\n\nschema_key\x18\x03 \x01(\t\x12\r\n\x05value\x18\x04 \x01(\x0c\x12\x1c\n\x14system_resource_name\x18\x05 \x01(\t\x12\x1b\n\x13system_resource_num\x18\x06 \x01(\x12\x12\x14\n\x0csearch_label\x18\x07 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'takasho.schema.common_featureset.resource.baas_product.v1_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BAASPRODUCT._serialized_start=196
  _BAASPRODUCT._serialized_end=354
  _BAASPRODUCTEXTRA._serialized_start=357
  _BAASPRODUCTEXTRA._serialized_end=614
# @@protoc_insertion_point(module_scope)
