# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: takasho/schema/common_featureset/resource/system/v1.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n9takasho/schema/common_featureset/resource/system/v1.proto\x12\x33takasho.schema.common_featureset.resource.system.v1\"a\n\nDeviceInfo\x12S\n\x08platform\x18\x01 \x01(\x0e\x32\x41.takasho.schema.common_featureset.resource.system.v1.PlatformType\"_\n\x0cPlayerStatus\x12\x0e\n\x06status\x18\x01 \x01(\x12\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x12\n\nexpired_at\x18\x03 \x01(\x12\x12\x16\n\x0ehas_expired_at\x18\x04 \x01(\x08\"\\\n\tBanStatus\x12\x0e\n\x06status\x18\x01 \x01(\x12\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x12\n\nexpired_at\x18\x03 \x01(\x12\x12\x16\n\x0ehas_expired_at\x18\x04 \x01(\x08*>\n\x0cPlatformType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\n\n\x06GOOGLE\x10\x01\x12\t\n\x05\x41PPLE\x10\x02\x12\n\n\x06\x45\x44ITOR\x10\x03*\x1c\n\x08\x42\x61\x61sType\x12\x07\n\x03NPF\x10\x00\x12\x07\n\x03LCX\x10\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'takasho.schema.common_featureset.resource.system.v1_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PLATFORMTYPE._serialized_start=404
  _PLATFORMTYPE._serialized_end=466
  _BAASTYPE._serialized_start=468
  _BAASTYPE._serialized_end=496
  _DEVICEINFO._serialized_start=114
  _DEVICEINFO._serialized_end=211
  _PLAYERSTATUS._serialized_start=213
  _PLAYERSTATUS._serialized_end=308
  _BANSTATUS._serialized_start=310
  _BANSTATUS._serialized_end=402
# @@protoc_insertion_point(module_scope)
