# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: takasho/schema/common_featureset/resource/game_status/v1.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n>takasho/schema/common_featureset/resource/game_status/v1.proto\x12\x38takasho.schema.common_featureset.resource.game_status.v1\"\x16\n\x05Value\x12\r\n\x05value\x18\x01 \x01(\x12\"\'\n\x06Status\x12\r\n\x05value\x18\x01 \x01(\x12\x12\x0e\n\x06status\x18\x02 \x01(\x08\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'takasho.schema.common_featureset.resource.game_status.v1_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VALUE._serialized_start=124
  _VALUE._serialized_end=146
  _STATUS._serialized_start=148
  _STATUS._serialized_end=187
# @@protoc_insertion_point(module_scope)
