# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: takasho/schema/common_featureset/resource/player_preference/v1.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nDtakasho/schema/common_featureset/resource/player_preference/v1.proto\x12>takasho.schema.common_featureset.resource.player_preference.v1\"\xc9\x03\n\x10PlayerPreference\x12\x12\n\nbirth_year\x18\x02 \x01(\x12\x12\x13\n\x0b\x62irth_month\x18\x03 \x01(\x12\x12\x0f\n\x07\x63ountry\x18\x04 \x01(\t\x12\x10\n\x08language\x18\x05 \x01(\t\x12\x0f\n\x07opt_out\x18\x06 \x01(\x08\x12\x1d\n\x15\x63onsented_tos_version\x18\x07 \x01(\t\x12\x12\n\ncreated_at\x18\x08 \x01(\x12\x12\x12\n\nupdated_at\x18\t \x01(\x12\x12\x10\n\x08nickname\x18\n \x01(\t\x12(\n consented_privacy_policy_version\x18\x0b \x01(\t\x12\x1b\n\x13nickname_updated_at\x18\x0c \x01(\x12\x12t\n\x14\x61llow_friend_request\x18\r \x01(\x0e\x32V.takasho.schema.common_featureset.resource.player_preference.v1.AllowFriendRequestType\x12\x19\n\x11max_friend_number\x18\x0e \x01(\x12\x12\'\n\x1fmax_friend_request_queue_length\x18\x0f \x01(\x12*J\n\x16\x41llowFriendRequestType\x12\x11\n\rNO_PREFERENCE\x10\x00\x12\r\n\tALLOW_ALL\x10\x01\x12\x0e\n\nFORBID_ALL\x10\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'takasho.schema.common_featureset.resource.player_preference.v1_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ALLOWFRIENDREQUESTTYPE._serialized_start=596
  _ALLOWFRIENDREQUESTTYPE._serialized_end=670
  _PLAYERPREFERENCE._serialized_start=137
  _PLAYERPREFERENCE._serialized_end=594
# @@protoc_insertion_point(module_scope)
