# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: takasho/schema/common_featureset/player_api/announcement.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from takasho.schema.common_featureset.resource.announcement import v1_pb2 as takasho_dot_schema_dot_common__featureset_dot_resource_dot_announcement_dot_v1__pb2
from takasho.schema.common_featureset.resource.extra_announcement import v1_pb2 as takasho_dot_schema_dot_common__featureset_dot_resource_dot_extra__announcement_dot_v1__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n>takasho/schema/common_featureset/player_api/announcement.proto\x12+takasho.schema.common_featureset.player_api\x1a?takasho/schema/common_featureset/resource/announcement/v1.proto\x1a\x45takasho/schema/common_featureset/resource/extra_announcement/v1.proto\"\x8f\x03\n\x1a\x41nnouncementGetAvailableV1\x1aI\n\x07Request\x12\x15\n\rlanguage_code\x18\x01 \x01(\t\x12\x12\n\npage_token\x18\x02 \x01(\t\x12\x13\n\x0bmax_results\x18\x03 \x01(\x04\x1a\xa5\x02\n\x08Response\x12^\n\rannouncements\x18\x01 \x03(\x0b\x32G.takasho.schema.common_featureset.resource.announcement.v1.Announcement\x12\x16\n\x0e\x62\x61se_image_url\x18\x02 \x01(\t\x12\x17\n\x0fnext_page_token\x18\x03 \x01(\t\x12\x17\n\x0fprev_page_token\x18\x04 \x01(\t\x12o\n\x13\x65xtra_announcements\x18\x05 \x03(\x0b\x32R.takasho.schema.common_featureset.resource.extra_announcement.v1.ExtraAnnouncement\"U\n\x1b\x41nnouncementGetCredentialV1\x1a\t\n\x07Request\x1a+\n\x08Response\x12\x12\n\ncredential\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t2\xc6\x01\n\x0c\x41nnouncement\x12\xb5\x01\n\x0eGetAvailableV1\x12O.takasho.schema.common_featureset.player_api.AnnouncementGetAvailableV1.Request\x1aP.takasho.schema.common_featureset.player_api.AnnouncementGetAvailableV1.Response\"\x00\x32\xcb\x01\n\x0e\x41nnouncementV2\x12\xb8\x01\n\x0fGetCredentialV1\x12P.takasho.schema.common_featureset.player_api.AnnouncementGetCredentialV1.Request\x1aQ.takasho.schema.common_featureset.player_api.AnnouncementGetCredentialV1.Response\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'takasho.schema.common_featureset.player_api.announcement_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ANNOUNCEMENTGETAVAILABLEV1._serialized_start=248
  _ANNOUNCEMENTGETAVAILABLEV1._serialized_end=647
  _ANNOUNCEMENTGETAVAILABLEV1_REQUEST._serialized_start=278
  _ANNOUNCEMENTGETAVAILABLEV1_REQUEST._serialized_end=351
  _ANNOUNCEMENTGETAVAILABLEV1_RESPONSE._serialized_start=354
  _ANNOUNCEMENTGETAVAILABLEV1_RESPONSE._serialized_end=647
  _ANNOUNCEMENTGETCREDENTIALV1._serialized_start=649
  _ANNOUNCEMENTGETCREDENTIALV1._serialized_end=734
  _ANNOUNCEMENTGETCREDENTIALV1_REQUEST._serialized_start=278
  _ANNOUNCEMENTGETCREDENTIALV1_REQUEST._serialized_end=287
  _ANNOUNCEMENTGETCREDENTIALV1_RESPONSE._serialized_start=691
  _ANNOUNCEMENTGETCREDENTIALV1_RESPONSE._serialized_end=734
  _ANNOUNCEMENT._serialized_start=737
  _ANNOUNCEMENT._serialized_end=935
  _ANNOUNCEMENTV2._serialized_start=938
  _ANNOUNCEMENTV2._serialized_end=1141
# @@protoc_insertion_point(module_scope)
