# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from takasho.schema.common_featureset.player_api import announcement_pb2 as takasho_dot_schema_dot_common__featureset_dot_player__api_dot_announcement__pb2


class AnnouncementStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAvailableV1 = channel.unary_unary(
                '/takasho.schema.common_featureset.player_api.Announcement/GetAvailableV1',
                request_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_announcement__pb2.AnnouncementGetAvailableV1.Request.SerializeToString,
                response_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_announcement__pb2.AnnouncementGetAvailableV1.Response.FromString,
                )


class AnnouncementServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAvailableV1(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnnouncementServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAvailableV1': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAvailableV1,
                    request_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_announcement__pb2.AnnouncementGetAvailableV1.Request.FromString,
                    response_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_announcement__pb2.AnnouncementGetAvailableV1.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'takasho.schema.common_featureset.player_api.Announcement', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Announcement(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAvailableV1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/takasho.schema.common_featureset.player_api.Announcement/GetAvailableV1',
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_announcement__pb2.AnnouncementGetAvailableV1.Request.SerializeToString,
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_announcement__pb2.AnnouncementGetAvailableV1.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class AnnouncementV2Stub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCredentialV1 = channel.unary_unary(
                '/takasho.schema.common_featureset.player_api.AnnouncementV2/GetCredentialV1',
                request_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_announcement__pb2.AnnouncementGetCredentialV1.Request.SerializeToString,
                response_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_announcement__pb2.AnnouncementGetCredentialV1.Response.FromString,
                )


class AnnouncementV2Servicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetCredentialV1(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnnouncementV2Servicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCredentialV1': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCredentialV1,
                    request_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_announcement__pb2.AnnouncementGetCredentialV1.Request.FromString,
                    response_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_announcement__pb2.AnnouncementGetCredentialV1.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'takasho.schema.common_featureset.player_api.AnnouncementV2', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AnnouncementV2(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCredentialV1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/takasho.schema.common_featureset.player_api.AnnouncementV2/GetCredentialV1',
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_announcement__pb2.AnnouncementGetCredentialV1.Request.SerializeToString,
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_announcement__pb2.AnnouncementGetCredentialV1.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
