# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: takasho/schema/common_featureset/player_api/baas_product.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from takasho.schema.common_featureset.resource.baas_product import v1_pb2 as takasho_dot_schema_dot_common__featureset_dot_resource_dot_baas__product_dot_v1__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n>takasho/schema/common_featureset/player_api/baas_product.proto\x12+takasho.schema.common_featureset.player_api\x1a?takasho/schema/common_featureset/resource/baas_product/v1.proto\"\xab\x01\n\x1e\x42\x61\x61sProductGetAvailableByIDsV1\x1a\x1e\n\x07Request\x12\x13\n\x0bproduct_ids\x18\x01 \x03(\t\x1ai\n\x08Response\x12]\n\rbaas_products\x18\x01 \x03(\x0b\x32\x46.takasho.schema.common_featureset.resource.baas_product.v1.BaasProduct2\xd2\x01\n\x0b\x42\x61\x61sProduct\x12\xc2\x01\n\x13GetAvailableByIDsV1\x12S.takasho.schema.common_featureset.player_api.BaasProductGetAvailableByIDsV1.Request\x1aT.takasho.schema.common_featureset.player_api.BaasProductGetAvailableByIDsV1.Response\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'takasho.schema.common_featureset.player_api.baas_product_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BAASPRODUCTGETAVAILABLEBYIDSV1._serialized_start=177
  _BAASPRODUCTGETAVAILABLEBYIDSV1._serialized_end=348
  _BAASPRODUCTGETAVAILABLEBYIDSV1_REQUEST._serialized_start=211
  _BAASPRODUCTGETAVAILABLEBYIDSV1_REQUEST._serialized_end=241
  _BAASPRODUCTGETAVAILABLEBYIDSV1_RESPONSE._serialized_start=243
  _BAASPRODUCTGETAVAILABLEBYIDSV1_RESPONSE._serialized_end=348
  _BAASPRODUCT._serialized_start=351
  _BAASPRODUCT._serialized_end=561
# @@protoc_insertion_point(module_scope)
