# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from takasho.schema.common_featureset.player_api import game_product_pb2 as takasho_dot_schema_dot_common__featureset_dot_player__api_dot_game__product__pb2


class GameProductStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAvailableV1 = channel.unary_unary(
                '/takasho.schema.common_featureset.player_api.GameProduct/GetAvailableV1',
                request_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_game__product__pb2.GameProductGetAvailableV1.Request.SerializeToString,
                response_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_game__product__pb2.GameProductGetAvailableV1.Response.FromString,
                )
        self.PurchaseV1 = channel.unary_unary(
                '/takasho.schema.common_featureset.player_api.GameProduct/PurchaseV1',
                request_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_game__product__pb2.GameProductPurchaseV1.Request.SerializeToString,
                response_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_game__product__pb2.GameProductPurchaseV1.Response.FromString,
                )
        self.PurchaseV2 = channel.unary_unary(
                '/takasho.schema.common_featureset.player_api.GameProduct/PurchaseV2',
                request_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_game__product__pb2.GameProductPurchaseV2.Request.SerializeToString,
                response_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_game__product__pb2.GameProductPurchaseV2.Response.FromString,
                )
        self.PurchaseAndSavePlayerStorageV1 = channel.unary_unary(
                '/takasho.schema.common_featureset.player_api.GameProduct/PurchaseAndSavePlayerStorageV1',
                request_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_game__product__pb2.GameProductPurchaseAndSavePlayerStorageV1.Request.SerializeToString,
                response_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_game__product__pb2.GameProductPurchaseAndSavePlayerStorageV1.Response.FromString,
                )
        self.PurchaseAndSavePlayerStorageV2 = channel.unary_unary(
                '/takasho.schema.common_featureset.player_api.GameProduct/PurchaseAndSavePlayerStorageV2',
                request_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_game__product__pb2.GameProductPurchaseAndSavePlayerStorageV2.Request.SerializeToString,
                response_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_game__product__pb2.GameProductPurchaseAndSavePlayerStorageV2.Response.FromString,
                )


class GameProductServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAvailableV1(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PurchaseV1(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PurchaseV2(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PurchaseAndSavePlayerStorageV1(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PurchaseAndSavePlayerStorageV2(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GameProductServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAvailableV1': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAvailableV1,
                    request_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_game__product__pb2.GameProductGetAvailableV1.Request.FromString,
                    response_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_game__product__pb2.GameProductGetAvailableV1.Response.SerializeToString,
            ),
            'PurchaseV1': grpc.unary_unary_rpc_method_handler(
                    servicer.PurchaseV1,
                    request_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_game__product__pb2.GameProductPurchaseV1.Request.FromString,
                    response_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_game__product__pb2.GameProductPurchaseV1.Response.SerializeToString,
            ),
            'PurchaseV2': grpc.unary_unary_rpc_method_handler(
                    servicer.PurchaseV2,
                    request_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_game__product__pb2.GameProductPurchaseV2.Request.FromString,
                    response_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_game__product__pb2.GameProductPurchaseV2.Response.SerializeToString,
            ),
            'PurchaseAndSavePlayerStorageV1': grpc.unary_unary_rpc_method_handler(
                    servicer.PurchaseAndSavePlayerStorageV1,
                    request_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_game__product__pb2.GameProductPurchaseAndSavePlayerStorageV1.Request.FromString,
                    response_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_game__product__pb2.GameProductPurchaseAndSavePlayerStorageV1.Response.SerializeToString,
            ),
            'PurchaseAndSavePlayerStorageV2': grpc.unary_unary_rpc_method_handler(
                    servicer.PurchaseAndSavePlayerStorageV2,
                    request_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_game__product__pb2.GameProductPurchaseAndSavePlayerStorageV2.Request.FromString,
                    response_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_game__product__pb2.GameProductPurchaseAndSavePlayerStorageV2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'takasho.schema.common_featureset.player_api.GameProduct', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GameProduct(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAvailableV1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/takasho.schema.common_featureset.player_api.GameProduct/GetAvailableV1',
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_game__product__pb2.GameProductGetAvailableV1.Request.SerializeToString,
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_game__product__pb2.GameProductGetAvailableV1.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PurchaseV1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/takasho.schema.common_featureset.player_api.GameProduct/PurchaseV1',
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_game__product__pb2.GameProductPurchaseV1.Request.SerializeToString,
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_game__product__pb2.GameProductPurchaseV1.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PurchaseV2(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/takasho.schema.common_featureset.player_api.GameProduct/PurchaseV2',
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_game__product__pb2.GameProductPurchaseV2.Request.SerializeToString,
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_game__product__pb2.GameProductPurchaseV2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PurchaseAndSavePlayerStorageV1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/takasho.schema.common_featureset.player_api.GameProduct/PurchaseAndSavePlayerStorageV1',
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_game__product__pb2.GameProductPurchaseAndSavePlayerStorageV1.Request.SerializeToString,
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_game__product__pb2.GameProductPurchaseAndSavePlayerStorageV1.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PurchaseAndSavePlayerStorageV2(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/takasho.schema.common_featureset.player_api.GameProduct/PurchaseAndSavePlayerStorageV2',
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_game__product__pb2.GameProductPurchaseAndSavePlayerStorageV2.Request.SerializeToString,
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_game__product__pb2.GameProductPurchaseAndSavePlayerStorageV2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
