# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: takasho/schema/common_featureset/player_api/game_status.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from takasho.schema.common_featureset.resource.game_status import v1_pb2 as takasho_dot_schema_dot_common__featureset_dot_resource_dot_game__status_dot_v1__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n=takasho/schema/common_featureset/player_api/game_status.proto\x12+takasho.schema.common_featureset.player_api\x1a>takasho/schema/common_featureset/resource/game_status/v1.proto\"\xcd\x01\n\x0fGameStatusGetV1\x1aZ\n\x07Request\x12O\n\x06values\x18\x01 \x03(\x0b\x32?.takasho.schema.common_featureset.resource.game_status.v1.Value\x1a^\n\x08Response\x12R\n\x08statuses\x18\x01 \x03(\x0b\x32@.takasho.schema.common_featureset.resource.game_status.v1.Status2\xa5\x01\n\nGameStatus\x12\x96\x01\n\x05GetV1\x12\x44.takasho.schema.common_featureset.player_api.GameStatusGetV1.Request\x1a\x45.takasho.schema.common_featureset.player_api.GameStatusGetV1.Response\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'takasho.schema.common_featureset.player_api.game_status_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GAMESTATUSGETV1._serialized_start=175
  _GAMESTATUSGETV1._serialized_end=380
  _GAMESTATUSGETV1_REQUEST._serialized_start=194
  _GAMESTATUSGETV1_REQUEST._serialized_end=284
  _GAMESTATUSGETV1_RESPONSE._serialized_start=286
  _GAMESTATUSGETV1_RESPONSE._serialized_end=380
  _GAMESTATUS._serialized_start=383
  _GAMESTATUS._serialized_end=548
# @@protoc_insertion_point(module_scope)
