# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: takasho/schema/common_featureset/player_api/ondemand_master.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from takasho.schema.common_featureset.resource.ondemand_master import v2_pb2 as takasho_dot_schema_dot_common__featureset_dot_resource_dot_ondemand__master_dot_v2__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nAtakasho/schema/common_featureset/player_api/ondemand_master.proto\x12+takasho.schema.common_featureset.player_api\x1a\x42takasho/schema/common_featureset/resource/ondemand_master/v2.proto\"\x97\x01\n\x1aOndemandMasterGetEntriesV2\x1a\x17\n\x07Request\x12\x0c\n\x04keys\x18\x01 \x03(\t\x1a`\n\x08Response\x12T\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x43.takasho.schema.common_featureset.resource.ondemand_master.v2.Entry2\xc4\x01\n\x0eOndemandMaster\x12\xb1\x01\n\x0cGetEntriesV1\x12O.takasho.schema.common_featureset.player_api.OndemandMasterGetEntriesV2.Request\x1aP.takasho.schema.common_featureset.player_api.OndemandMasterGetEntriesV2.Responseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'takasho.schema.common_featureset.player_api.ondemand_master_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ONDEMANDMASTERGETENTRIESV2._serialized_start=183
  _ONDEMANDMASTERGETENTRIESV2._serialized_end=334
  _ONDEMANDMASTERGETENTRIESV2_REQUEST._serialized_start=213
  _ONDEMANDMASTERGETENTRIESV2_REQUEST._serialized_end=236
  _ONDEMANDMASTERGETENTRIESV2_RESPONSE._serialized_start=238
  _ONDEMANDMASTERGETENTRIESV2_RESPONSE._serialized_end=334
  _ONDEMANDMASTER._serialized_start=337
  _ONDEMANDMASTER._serialized_end=533
# @@protoc_insertion_point(module_scope)
