# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from takasho.schema.common_featureset.player_api import player_event_log_pb2 as takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__event__log__pb2


class PlayerEventLogStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendV1 = channel.unary_unary(
                '/takasho.schema.common_featureset.player_api.PlayerEventLog/SendV1',
                request_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__event__log__pb2.PlayerEventLogSendV1.Request.SerializeToString,
                response_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__event__log__pb2.PlayerEventLogSendV1.Response.FromString,
                )


class PlayerEventLogServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendV1(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PlayerEventLogServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendV1': grpc.unary_unary_rpc_method_handler(
                    servicer.SendV1,
                    request_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__event__log__pb2.PlayerEventLogSendV1.Request.FromString,
                    response_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__event__log__pb2.PlayerEventLogSendV1.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'takasho.schema.common_featureset.player_api.PlayerEventLog', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PlayerEventLog(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendV1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/takasho.schema.common_featureset.player_api.PlayerEventLog/SendV1',
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__event__log__pb2.PlayerEventLogSendV1.Request.SerializeToString,
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__event__log__pb2.PlayerEventLogSendV1.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
