# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from takasho.schema.common_featureset.player_api import player_achievement_pb2 as takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__achievement__pb2


class PlayerAchievementStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAvailableV1 = channel.unary_unary(
                '/takasho.schema.common_featureset.player_api.PlayerAchievement/GetAvailableV1',
                request_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__achievement__pb2.PlayerAchievementGetAvailableV1.Request.SerializeToString,
                response_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__achievement__pb2.PlayerAchievementGetAvailableV1.Response.FromString,
                )
        self.GetAvailableByIDsV1 = channel.unary_unary(
                '/takasho.schema.common_featureset.player_api.PlayerAchievement/GetAvailableByIDsV1',
                request_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__achievement__pb2.PlayerAchievementGetAvailableByIDsV1.Request.SerializeToString,
                response_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__achievement__pb2.PlayerAchievementGetAvailableByIDsV1.Response.FromString,
                )
        self.UnlockV1 = channel.unary_unary(
                '/takasho.schema.common_featureset.player_api.PlayerAchievement/UnlockV1',
                request_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__achievement__pb2.PlayerAchievementUnlockV1.Request.SerializeToString,
                response_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__achievement__pb2.PlayerAchievementUnlockV1.Response.FromString,
                )
        self.UnlockAndSavePlayerStorageV1 = channel.unary_unary(
                '/takasho.schema.common_featureset.player_api.PlayerAchievement/UnlockAndSavePlayerStorageV1',
                request_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__achievement__pb2.PlayerAchievementUnlockAndSavePlayerStorageV1.Request.SerializeToString,
                response_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__achievement__pb2.PlayerAchievementUnlockAndSavePlayerStorageV1.Response.FromString,
                )


class PlayerAchievementServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAvailableV1(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAvailableByIDsV1(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnlockV1(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnlockAndSavePlayerStorageV1(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PlayerAchievementServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAvailableV1': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAvailableV1,
                    request_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__achievement__pb2.PlayerAchievementGetAvailableV1.Request.FromString,
                    response_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__achievement__pb2.PlayerAchievementGetAvailableV1.Response.SerializeToString,
            ),
            'GetAvailableByIDsV1': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAvailableByIDsV1,
                    request_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__achievement__pb2.PlayerAchievementGetAvailableByIDsV1.Request.FromString,
                    response_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__achievement__pb2.PlayerAchievementGetAvailableByIDsV1.Response.SerializeToString,
            ),
            'UnlockV1': grpc.unary_unary_rpc_method_handler(
                    servicer.UnlockV1,
                    request_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__achievement__pb2.PlayerAchievementUnlockV1.Request.FromString,
                    response_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__achievement__pb2.PlayerAchievementUnlockV1.Response.SerializeToString,
            ),
            'UnlockAndSavePlayerStorageV1': grpc.unary_unary_rpc_method_handler(
                    servicer.UnlockAndSavePlayerStorageV1,
                    request_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__achievement__pb2.PlayerAchievementUnlockAndSavePlayerStorageV1.Request.FromString,
                    response_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__achievement__pb2.PlayerAchievementUnlockAndSavePlayerStorageV1.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'takasho.schema.common_featureset.player_api.PlayerAchievement', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PlayerAchievement(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAvailableV1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/takasho.schema.common_featureset.player_api.PlayerAchievement/GetAvailableV1',
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__achievement__pb2.PlayerAchievementGetAvailableV1.Request.SerializeToString,
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__achievement__pb2.PlayerAchievementGetAvailableV1.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAvailableByIDsV1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/takasho.schema.common_featureset.player_api.PlayerAchievement/GetAvailableByIDsV1',
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__achievement__pb2.PlayerAchievementGetAvailableByIDsV1.Request.SerializeToString,
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__achievement__pb2.PlayerAchievementGetAvailableByIDsV1.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UnlockV1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/takasho.schema.common_featureset.player_api.PlayerAchievement/UnlockV1',
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__achievement__pb2.PlayerAchievementUnlockV1.Request.SerializeToString,
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__achievement__pb2.PlayerAchievementUnlockV1.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UnlockAndSavePlayerStorageV1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/takasho.schema.common_featureset.player_api.PlayerAchievement/UnlockAndSavePlayerStorageV1',
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__achievement__pb2.PlayerAchievementUnlockAndSavePlayerStorageV1.Request.SerializeToString,
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__achievement__pb2.PlayerAchievementUnlockAndSavePlayerStorageV1.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
