# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from takasho.schema.common_featureset.player_api import player_preference_pb2 as takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__preference__pb2


class PlayerPreferenceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPreferenceV1 = channel.unary_unary(
                '/takasho.schema.common_featureset.player_api.PlayerPreference/GetPreferenceV1',
                request_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__preference__pb2.PlayerPreferenceGetPreferenceV1.Request.SerializeToString,
                response_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__preference__pb2.PlayerPreferenceGetPreferenceV1.Response.FromString,
                )
        self.SetPreferenceV1 = channel.unary_unary(
                '/takasho.schema.common_featureset.player_api.PlayerPreference/SetPreferenceV1',
                request_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__preference__pb2.PlayerPreferenceSetPreferenceV1.Request.SerializeToString,
                response_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__preference__pb2.PlayerPreferenceSetPreferenceV1.Response.FromString,
                )
        self.SetPreferenceAndSavePlayerStorageV1 = channel.unary_unary(
                '/takasho.schema.common_featureset.player_api.PlayerPreference/SetPreferenceAndSavePlayerStorageV1',
                request_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__preference__pb2.PlayerPreferenceSetPreferenceAndSavePlayerStorageV1.Request.SerializeToString,
                response_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__preference__pb2.PlayerPreferenceSetPreferenceAndSavePlayerStorageV1.Response.FromString,
                )
        self.GetMonthlyBillingLimitV1 = channel.unary_unary(
                '/takasho.schema.common_featureset.player_api.PlayerPreference/GetMonthlyBillingLimitV1',
                request_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__preference__pb2.PlayerPreferenceGetMonthlyBillingLimitV1.Request.SerializeToString,
                response_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__preference__pb2.PlayerPreferenceGetMonthlyBillingLimitV1.Response.FromString,
                )
        self.GetMonthlyPurchaseSummaryV1 = channel.unary_unary(
                '/takasho.schema.common_featureset.player_api.PlayerPreference/GetMonthlyPurchaseSummaryV1',
                request_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__preference__pb2.PlayerPreferenceGetMonthlyPurchaseSummaryV1.Request.SerializeToString,
                response_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__preference__pb2.PlayerPreferenceGetMonthlyPurchaseSummaryV1.Response.FromString,
                )


class PlayerPreferenceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPreferenceV1(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetPreferenceV1(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetPreferenceAndSavePlayerStorageV1(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMonthlyBillingLimitV1(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMonthlyPurchaseSummaryV1(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PlayerPreferenceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPreferenceV1': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPreferenceV1,
                    request_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__preference__pb2.PlayerPreferenceGetPreferenceV1.Request.FromString,
                    response_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__preference__pb2.PlayerPreferenceGetPreferenceV1.Response.SerializeToString,
            ),
            'SetPreferenceV1': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPreferenceV1,
                    request_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__preference__pb2.PlayerPreferenceSetPreferenceV1.Request.FromString,
                    response_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__preference__pb2.PlayerPreferenceSetPreferenceV1.Response.SerializeToString,
            ),
            'SetPreferenceAndSavePlayerStorageV1': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPreferenceAndSavePlayerStorageV1,
                    request_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__preference__pb2.PlayerPreferenceSetPreferenceAndSavePlayerStorageV1.Request.FromString,
                    response_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__preference__pb2.PlayerPreferenceSetPreferenceAndSavePlayerStorageV1.Response.SerializeToString,
            ),
            'GetMonthlyBillingLimitV1': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMonthlyBillingLimitV1,
                    request_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__preference__pb2.PlayerPreferenceGetMonthlyBillingLimitV1.Request.FromString,
                    response_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__preference__pb2.PlayerPreferenceGetMonthlyBillingLimitV1.Response.SerializeToString,
            ),
            'GetMonthlyPurchaseSummaryV1': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMonthlyPurchaseSummaryV1,
                    request_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__preference__pb2.PlayerPreferenceGetMonthlyPurchaseSummaryV1.Request.FromString,
                    response_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__preference__pb2.PlayerPreferenceGetMonthlyPurchaseSummaryV1.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'takasho.schema.common_featureset.player_api.PlayerPreference', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PlayerPreference(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPreferenceV1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/takasho.schema.common_featureset.player_api.PlayerPreference/GetPreferenceV1',
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__preference__pb2.PlayerPreferenceGetPreferenceV1.Request.SerializeToString,
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__preference__pb2.PlayerPreferenceGetPreferenceV1.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetPreferenceV1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/takasho.schema.common_featureset.player_api.PlayerPreference/SetPreferenceV1',
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__preference__pb2.PlayerPreferenceSetPreferenceV1.Request.SerializeToString,
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__preference__pb2.PlayerPreferenceSetPreferenceV1.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetPreferenceAndSavePlayerStorageV1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/takasho.schema.common_featureset.player_api.PlayerPreference/SetPreferenceAndSavePlayerStorageV1',
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__preference__pb2.PlayerPreferenceSetPreferenceAndSavePlayerStorageV1.Request.SerializeToString,
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__preference__pb2.PlayerPreferenceSetPreferenceAndSavePlayerStorageV1.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMonthlyBillingLimitV1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/takasho.schema.common_featureset.player_api.PlayerPreference/GetMonthlyBillingLimitV1',
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__preference__pb2.PlayerPreferenceGetMonthlyBillingLimitV1.Request.SerializeToString,
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__preference__pb2.PlayerPreferenceGetMonthlyBillingLimitV1.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMonthlyPurchaseSummaryV1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/takasho.schema.common_featureset.player_api.PlayerPreference/GetMonthlyPurchaseSummaryV1',
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__preference__pb2.PlayerPreferenceGetMonthlyPurchaseSummaryV1.Request.SerializeToString,
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__preference__pb2.PlayerPreferenceGetMonthlyPurchaseSummaryV1.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
