# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from takasho.schema.common_featureset.player_api import player_key_value_store_pb2 as takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__key__value__store__pb2


class PlayerKeyValueStoreStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPlayerKeyValuesV1 = channel.unary_unary(
                '/takasho.schema.common_featureset.player_api.PlayerKeyValueStore/GetPlayerKeyValuesV1',
                request_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__key__value__store__pb2.PlayerKeyValueStoreGetPlayerKeyValuesV1.Request.SerializeToString,
                response_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__key__value__store__pb2.PlayerKeyValueStoreGetPlayerKeyValuesV1.Response.FromString,
                )
        self.IncrementPlayerKeyValuesV1 = channel.unary_unary(
                '/takasho.schema.common_featureset.player_api.PlayerKeyValueStore/IncrementPlayerKeyValuesV1',
                request_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__key__value__store__pb2.PlayerKeyValueStoreIncrementPlayerKeyValuesV1.Request.SerializeToString,
                response_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__key__value__store__pb2.PlayerKeyValueStoreIncrementPlayerKeyValuesV1.Response.FromString,
                )
        self.IncrementPlayerKeyValuesAndSavePlayerStorageV1 = channel.unary_unary(
                '/takasho.schema.common_featureset.player_api.PlayerKeyValueStore/IncrementPlayerKeyValuesAndSavePlayerStorageV1',
                request_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__key__value__store__pb2.PlayerKeyValueStoreIncrementPlayerKeyValuesAndSavePlayerStorageV1.Request.SerializeToString,
                response_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__key__value__store__pb2.PlayerKeyValueStoreIncrementPlayerKeyValuesAndSavePlayerStorageV1.Response.FromString,
                )
        self.UpdatePlayerKeyValuesAndSavePlayerStorageV1 = channel.unary_unary(
                '/takasho.schema.common_featureset.player_api.PlayerKeyValueStore/UpdatePlayerKeyValuesAndSavePlayerStorageV1',
                request_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__key__value__store__pb2.PlayerKeyValueStoreUpdatePlayerKeyValuesAndSavePlayerStorageV1.Request.SerializeToString,
                response_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__key__value__store__pb2.PlayerKeyValueStoreUpdatePlayerKeyValuesAndSavePlayerStorageV1.Response.FromString,
                )


class PlayerKeyValueStoreServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPlayerKeyValuesV1(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IncrementPlayerKeyValuesV1(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IncrementPlayerKeyValuesAndSavePlayerStorageV1(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePlayerKeyValuesAndSavePlayerStorageV1(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PlayerKeyValueStoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPlayerKeyValuesV1': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlayerKeyValuesV1,
                    request_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__key__value__store__pb2.PlayerKeyValueStoreGetPlayerKeyValuesV1.Request.FromString,
                    response_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__key__value__store__pb2.PlayerKeyValueStoreGetPlayerKeyValuesV1.Response.SerializeToString,
            ),
            'IncrementPlayerKeyValuesV1': grpc.unary_unary_rpc_method_handler(
                    servicer.IncrementPlayerKeyValuesV1,
                    request_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__key__value__store__pb2.PlayerKeyValueStoreIncrementPlayerKeyValuesV1.Request.FromString,
                    response_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__key__value__store__pb2.PlayerKeyValueStoreIncrementPlayerKeyValuesV1.Response.SerializeToString,
            ),
            'IncrementPlayerKeyValuesAndSavePlayerStorageV1': grpc.unary_unary_rpc_method_handler(
                    servicer.IncrementPlayerKeyValuesAndSavePlayerStorageV1,
                    request_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__key__value__store__pb2.PlayerKeyValueStoreIncrementPlayerKeyValuesAndSavePlayerStorageV1.Request.FromString,
                    response_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__key__value__store__pb2.PlayerKeyValueStoreIncrementPlayerKeyValuesAndSavePlayerStorageV1.Response.SerializeToString,
            ),
            'UpdatePlayerKeyValuesAndSavePlayerStorageV1': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePlayerKeyValuesAndSavePlayerStorageV1,
                    request_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__key__value__store__pb2.PlayerKeyValueStoreUpdatePlayerKeyValuesAndSavePlayerStorageV1.Request.FromString,
                    response_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__key__value__store__pb2.PlayerKeyValueStoreUpdatePlayerKeyValuesAndSavePlayerStorageV1.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'takasho.schema.common_featureset.player_api.PlayerKeyValueStore', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PlayerKeyValueStore(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPlayerKeyValuesV1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/takasho.schema.common_featureset.player_api.PlayerKeyValueStore/GetPlayerKeyValuesV1',
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__key__value__store__pb2.PlayerKeyValueStoreGetPlayerKeyValuesV1.Request.SerializeToString,
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__key__value__store__pb2.PlayerKeyValueStoreGetPlayerKeyValuesV1.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def IncrementPlayerKeyValuesV1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/takasho.schema.common_featureset.player_api.PlayerKeyValueStore/IncrementPlayerKeyValuesV1',
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__key__value__store__pb2.PlayerKeyValueStoreIncrementPlayerKeyValuesV1.Request.SerializeToString,
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__key__value__store__pb2.PlayerKeyValueStoreIncrementPlayerKeyValuesV1.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def IncrementPlayerKeyValuesAndSavePlayerStorageV1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/takasho.schema.common_featureset.player_api.PlayerKeyValueStore/IncrementPlayerKeyValuesAndSavePlayerStorageV1',
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__key__value__store__pb2.PlayerKeyValueStoreIncrementPlayerKeyValuesAndSavePlayerStorageV1.Request.SerializeToString,
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__key__value__store__pb2.PlayerKeyValueStoreIncrementPlayerKeyValuesAndSavePlayerStorageV1.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdatePlayerKeyValuesAndSavePlayerStorageV1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/takasho.schema.common_featureset.player_api.PlayerKeyValueStore/UpdatePlayerKeyValuesAndSavePlayerStorageV1',
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__key__value__store__pb2.PlayerKeyValueStoreUpdatePlayerKeyValuesAndSavePlayerStorageV1.Request.SerializeToString,
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__key__value__store__pb2.PlayerKeyValueStoreUpdatePlayerKeyValuesAndSavePlayerStorageV1.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
