# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: takasho/schema/common_featureset/player_api/player_event_log.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from takasho.schema.common_featureset.resource.player_event_log import v1_pb2 as takasho_dot_schema_dot_common__featureset_dot_resource_dot_player__event__log_dot_v1__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nBtakasho/schema/common_featureset/player_api/player_event_log.proto\x12+takasho.schema.common_featureset.player_api\x1a\x43takasho/schema/common_featureset/resource/player_event_log/v1.proto\"\x97\x01\n\x14PlayerEventLogSendV1\x1as\n\x07Request\x12h\n\x11player_event_logs\x18\x01 \x03(\x0b\x32M.takasho.schema.common_featureset.resource.player_event_log.v1.PlayerEventLog\x1a\n\n\x08Response2\xb4\x01\n\x0ePlayerEventLog\x12\xa1\x01\n\x06SendV1\x12I.takasho.schema.common_featureset.player_api.PlayerEventLogSendV1.Request\x1aJ.takasho.schema.common_featureset.player_api.PlayerEventLogSendV1.Response\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'takasho.schema.common_featureset.player_api.player_event_log_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PLAYEREVENTLOGSENDV1._serialized_start=185
  _PLAYEREVENTLOGSENDV1._serialized_end=336
  _PLAYEREVENTLOGSENDV1_REQUEST._serialized_start=209
  _PLAYEREVENTLOGSENDV1_REQUEST._serialized_end=324
  _PLAYEREVENTLOGSENDV1_RESPONSE._serialized_start=326
  _PLAYEREVENTLOGSENDV1_RESPONSE._serialized_end=336
  _PLAYEREVENTLOG._serialized_start=339
  _PLAYEREVENTLOG._serialized_end=519
# @@protoc_insertion_point(module_scope)
