# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from takasho.schema.common_featureset.player_api import player_inventory_pb2 as takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__inventory__pb2


class PlayerInventoryStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetInventoriesV1 = channel.unary_unary(
                '/takasho.schema.common_featureset.player_api.PlayerInventory/GetInventoriesV1',
                request_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__inventory__pb2.PlayerInventoryGetInventoriesV1.Request.SerializeToString,
                response_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__inventory__pb2.PlayerInventoryGetInventoriesV1.Response.FromString,
                )
        self.GetReceivedInventoriesV1 = channel.unary_unary(
                '/takasho.schema.common_featureset.player_api.PlayerInventory/GetReceivedInventoriesV1',
                request_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__inventory__pb2.PlayerInventoryGetReceivedInventoriesV1.Request.SerializeToString,
                response_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__inventory__pb2.PlayerInventoryGetReceivedInventoriesV1.Response.FromString,
                )
        self.ReceiveV1 = channel.unary_unary(
                '/takasho.schema.common_featureset.player_api.PlayerInventory/ReceiveV1',
                request_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__inventory__pb2.PlayerInventoryReceiveV1.Request.SerializeToString,
                response_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__inventory__pb2.PlayerInventoryReceiveV1.Response.FromString,
                )
        self.GetInventoriesAndCountV1 = channel.unary_unary(
                '/takasho.schema.common_featureset.player_api.PlayerInventory/GetInventoriesAndCountV1',
                request_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__inventory__pb2.PlayerInventoryGetInventoriesAndCountV1.Request.SerializeToString,
                response_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__inventory__pb2.PlayerInventoryGetInventoriesAndCountV1.Response.FromString,
                )


class PlayerInventoryServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetInventoriesV1(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReceivedInventoriesV1(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReceiveV1(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInventoriesAndCountV1(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PlayerInventoryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetInventoriesV1': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInventoriesV1,
                    request_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__inventory__pb2.PlayerInventoryGetInventoriesV1.Request.FromString,
                    response_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__inventory__pb2.PlayerInventoryGetInventoriesV1.Response.SerializeToString,
            ),
            'GetReceivedInventoriesV1': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReceivedInventoriesV1,
                    request_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__inventory__pb2.PlayerInventoryGetReceivedInventoriesV1.Request.FromString,
                    response_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__inventory__pb2.PlayerInventoryGetReceivedInventoriesV1.Response.SerializeToString,
            ),
            'ReceiveV1': grpc.unary_unary_rpc_method_handler(
                    servicer.ReceiveV1,
                    request_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__inventory__pb2.PlayerInventoryReceiveV1.Request.FromString,
                    response_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__inventory__pb2.PlayerInventoryReceiveV1.Response.SerializeToString,
            ),
            'GetInventoriesAndCountV1': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInventoriesAndCountV1,
                    request_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__inventory__pb2.PlayerInventoryGetInventoriesAndCountV1.Request.FromString,
                    response_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__inventory__pb2.PlayerInventoryGetInventoriesAndCountV1.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'takasho.schema.common_featureset.player_api.PlayerInventory', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PlayerInventory(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetInventoriesV1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/takasho.schema.common_featureset.player_api.PlayerInventory/GetInventoriesV1',
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__inventory__pb2.PlayerInventoryGetInventoriesV1.Request.SerializeToString,
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__inventory__pb2.PlayerInventoryGetInventoriesV1.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetReceivedInventoriesV1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/takasho.schema.common_featureset.player_api.PlayerInventory/GetReceivedInventoriesV1',
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__inventory__pb2.PlayerInventoryGetReceivedInventoriesV1.Request.SerializeToString,
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__inventory__pb2.PlayerInventoryGetReceivedInventoriesV1.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReceiveV1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/takasho.schema.common_featureset.player_api.PlayerInventory/ReceiveV1',
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__inventory__pb2.PlayerInventoryReceiveV1.Request.SerializeToString,
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__inventory__pb2.PlayerInventoryReceiveV1.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetInventoriesAndCountV1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/takasho.schema.common_featureset.player_api.PlayerInventory/GetInventoriesAndCountV1',
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__inventory__pb2.PlayerInventoryGetInventoriesAndCountV1.Request.SerializeToString,
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_player__inventory__pb2.PlayerInventoryGetInventoriesAndCountV1.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
