# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: takasho/schema/common_featureset/player_api/push_notification.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nCtakasho/schema/common_featureset/player_api/push_notification.proto\x12+takasho.schema.common_featureset.player_api\"`\n\x1bPushNotificationSetConfigV1\x1a\x1d\n\x07Request\x12\x12\n\nreceivable\x18\x01 \x01(\x08\x1a\x1e\n\x08Response\x12\x12\n\nreceivable\x18\x01 \x01(\x08:\x02\x18\x01\"G\n\x1bPushNotificationSetConfigV2\x1a\x1c\n\x07Request\x12\x11\n\ttopic_ids\x18\x01 \x03(\t\x1a\n\n\x08Response\"L\n\x1bPushNotificationGetConfigV1\x1a\t\n\x07Request\x1a\x1e\n\x08Response\x12\x12\n\nreceivable\x18\x01 \x01(\x08:\x02\x18\x01\"G\n\x1bPushNotificationGetConfigV2\x1a\t\n\x07Request\x1a\x1d\n\x08Response\x12\x11\n\ttopic_ids\x18\x01 \x03(\t2\xee\x05\n\x10PushNotification\x12\xb4\x01\n\x0bSetConfigV1\x12P.takasho.schema.common_featureset.player_api.PushNotificationSetConfigV1.Request\x1aQ.takasho.schema.common_featureset.player_api.PushNotificationSetConfigV1.Response\"\x00\x12\xb4\x01\n\x0bSetConfigV2\x12P.takasho.schema.common_featureset.player_api.PushNotificationSetConfigV2.Request\x1aQ.takasho.schema.common_featureset.player_api.PushNotificationSetConfigV2.Response\"\x00\x12\xb4\x01\n\x0bGetConfigV1\x12P.takasho.schema.common_featureset.player_api.PushNotificationGetConfigV1.Request\x1aQ.takasho.schema.common_featureset.player_api.PushNotificationGetConfigV1.Response\"\x00\x12\xb4\x01\n\x0bGetConfigV2\x12P.takasho.schema.common_featureset.player_api.PushNotificationGetConfigV2.Request\x1aQ.takasho.schema.common_featureset.player_api.PushNotificationGetConfigV2.Response\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'takasho.schema.common_featureset.player_api.push_notification_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PUSHNOTIFICATIONSETCONFIGV1._options = None
  _PUSHNOTIFICATIONSETCONFIGV1._serialized_options = b'\030\001'
  _PUSHNOTIFICATIONGETCONFIGV1._options = None
  _PUSHNOTIFICATIONGETCONFIGV1._serialized_options = b'\030\001'
  _PUSHNOTIFICATIONSETCONFIGV1._serialized_start=116
  _PUSHNOTIFICATIONSETCONFIGV1._serialized_end=212
  _PUSHNOTIFICATIONSETCONFIGV1_REQUEST._serialized_start=147
  _PUSHNOTIFICATIONSETCONFIGV1_REQUEST._serialized_end=176
  _PUSHNOTIFICATIONSETCONFIGV1_RESPONSE._serialized_start=178
  _PUSHNOTIFICATIONSETCONFIGV1_RESPONSE._serialized_end=208
  _PUSHNOTIFICATIONSETCONFIGV2._serialized_start=214
  _PUSHNOTIFICATIONSETCONFIGV2._serialized_end=285
  _PUSHNOTIFICATIONSETCONFIGV2_REQUEST._serialized_start=245
  _PUSHNOTIFICATIONSETCONFIGV2_REQUEST._serialized_end=273
  _PUSHNOTIFICATIONSETCONFIGV2_RESPONSE._serialized_start=178
  _PUSHNOTIFICATIONSETCONFIGV2_RESPONSE._serialized_end=188
  _PUSHNOTIFICATIONGETCONFIGV1._serialized_start=287
  _PUSHNOTIFICATIONGETCONFIGV1._serialized_end=363
  _PUSHNOTIFICATIONGETCONFIGV1_REQUEST._serialized_start=147
  _PUSHNOTIFICATIONGETCONFIGV1_REQUEST._serialized_end=156
  _PUSHNOTIFICATIONGETCONFIGV1_RESPONSE._serialized_start=178
  _PUSHNOTIFICATIONGETCONFIGV1_RESPONSE._serialized_end=208
  _PUSHNOTIFICATIONGETCONFIGV2._serialized_start=365
  _PUSHNOTIFICATIONGETCONFIGV2._serialized_end=436
  _PUSHNOTIFICATIONGETCONFIGV2_REQUEST._serialized_start=147
  _PUSHNOTIFICATIONGETCONFIGV2_REQUEST._serialized_end=156
  _PUSHNOTIFICATIONGETCONFIGV2_RESPONSE._serialized_start=407
  _PUSHNOTIFICATIONGETCONFIGV2_RESPONSE._serialized_end=436
  _PUSHNOTIFICATION._serialized_start=439
  _PUSHNOTIFICATION._serialized_end=1189
# @@protoc_insertion_point(module_scope)
