# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from takasho.schema.common_featureset.player_api import step_up_loot_box_pb2 as takasho_dot_schema_dot_common__featureset_dot_player__api_dot_step__up__loot__box__pb2


class StepUpLootBoxStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAvailableV1 = channel.unary_unary(
                '/takasho.schema.common_featureset.player_api.StepUpLootBox/GetAvailableV1',
                request_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_step__up__loot__box__pb2.StepUpLootBoxGetAvailableV1.Request.SerializeToString,
                response_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_step__up__loot__box__pb2.StepUpLootBoxGetAvailableV1.Response.FromString,
                )
        self.PurchaseV1 = channel.unary_unary(
                '/takasho.schema.common_featureset.player_api.StepUpLootBox/PurchaseV1',
                request_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_step__up__loot__box__pb2.StepUpLootBoxPurchaseV1.Request.SerializeToString,
                response_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_step__up__loot__box__pb2.StepUpLootBoxPurchaseV1.Response.FromString,
                )
        self.GetProbabilityV1 = channel.unary_unary(
                '/takasho.schema.common_featureset.player_api.StepUpLootBox/GetProbabilityV1',
                request_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_step__up__loot__box__pb2.StepUpLootBoxGetProbabilityV1.Request.SerializeToString,
                response_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_step__up__loot__box__pb2.StepUpLootBoxGetProbabilityV1.Response.FromString,
                )
        self.GetDetailV1 = channel.unary_unary(
                '/takasho.schema.common_featureset.player_api.StepUpLootBox/GetDetailV1',
                request_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_step__up__loot__box__pb2.StepUpLootBoxGetDetailV1.Request.SerializeToString,
                response_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_step__up__loot__box__pb2.StepUpLootBoxGetDetailV1.Response.FromString,
                )


class StepUpLootBoxServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAvailableV1(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PurchaseV1(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProbabilityV1(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDetailV1(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StepUpLootBoxServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAvailableV1': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAvailableV1,
                    request_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_step__up__loot__box__pb2.StepUpLootBoxGetAvailableV1.Request.FromString,
                    response_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_step__up__loot__box__pb2.StepUpLootBoxGetAvailableV1.Response.SerializeToString,
            ),
            'PurchaseV1': grpc.unary_unary_rpc_method_handler(
                    servicer.PurchaseV1,
                    request_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_step__up__loot__box__pb2.StepUpLootBoxPurchaseV1.Request.FromString,
                    response_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_step__up__loot__box__pb2.StepUpLootBoxPurchaseV1.Response.SerializeToString,
            ),
            'GetProbabilityV1': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProbabilityV1,
                    request_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_step__up__loot__box__pb2.StepUpLootBoxGetProbabilityV1.Request.FromString,
                    response_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_step__up__loot__box__pb2.StepUpLootBoxGetProbabilityV1.Response.SerializeToString,
            ),
            'GetDetailV1': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDetailV1,
                    request_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_step__up__loot__box__pb2.StepUpLootBoxGetDetailV1.Request.FromString,
                    response_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_step__up__loot__box__pb2.StepUpLootBoxGetDetailV1.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'takasho.schema.common_featureset.player_api.StepUpLootBox', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class StepUpLootBox(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAvailableV1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/takasho.schema.common_featureset.player_api.StepUpLootBox/GetAvailableV1',
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_step__up__loot__box__pb2.StepUpLootBoxGetAvailableV1.Request.SerializeToString,
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_step__up__loot__box__pb2.StepUpLootBoxGetAvailableV1.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PurchaseV1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/takasho.schema.common_featureset.player_api.StepUpLootBox/PurchaseV1',
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_step__up__loot__box__pb2.StepUpLootBoxPurchaseV1.Request.SerializeToString,
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_step__up__loot__box__pb2.StepUpLootBoxPurchaseV1.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetProbabilityV1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/takasho.schema.common_featureset.player_api.StepUpLootBox/GetProbabilityV1',
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_step__up__loot__box__pb2.StepUpLootBoxGetProbabilityV1.Request.SerializeToString,
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_step__up__loot__box__pb2.StepUpLootBoxGetProbabilityV1.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDetailV1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/takasho.schema.common_featureset.player_api.StepUpLootBox/GetDetailV1',
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_step__up__loot__box__pb2.StepUpLootBoxGetDetailV1.Request.SerializeToString,
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_step__up__loot__box__pb2.StepUpLootBoxGetDetailV1.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class StepUpLootBoxV2Stub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAvailableV1 = channel.unary_unary(
                '/takasho.schema.common_featureset.player_api.StepUpLootBoxV2/GetAvailableV1',
                request_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_step__up__loot__box__pb2.StepUpLootBoxV2GetAvailableV1.Request.SerializeToString,
                response_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_step__up__loot__box__pb2.StepUpLootBoxV2GetAvailableV1.Response.FromString,
                )
        self.PurchaseV1 = channel.unary_unary(
                '/takasho.schema.common_featureset.player_api.StepUpLootBoxV2/PurchaseV1',
                request_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_step__up__loot__box__pb2.StepUpLootBoxV2PurchaseV1.Request.SerializeToString,
                response_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_step__up__loot__box__pb2.StepUpLootBoxV2PurchaseV1.Response.FromString,
                )
        self.GetProbabilityV1 = channel.unary_unary(
                '/takasho.schema.common_featureset.player_api.StepUpLootBoxV2/GetProbabilityV1',
                request_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_step__up__loot__box__pb2.StepUpLootBoxV2GetProbabilityV1.Request.SerializeToString,
                response_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_step__up__loot__box__pb2.StepUpLootBoxV2GetProbabilityV1.Response.FromString,
                )
        self.GetDetailV1 = channel.unary_unary(
                '/takasho.schema.common_featureset.player_api.StepUpLootBoxV2/GetDetailV1',
                request_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_step__up__loot__box__pb2.StepUpLootBoxV2GetDetailV1.Request.SerializeToString,
                response_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_step__up__loot__box__pb2.StepUpLootBoxV2GetDetailV1.Response.FromString,
                )


class StepUpLootBoxV2Servicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAvailableV1(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PurchaseV1(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProbabilityV1(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDetailV1(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StepUpLootBoxV2Servicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAvailableV1': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAvailableV1,
                    request_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_step__up__loot__box__pb2.StepUpLootBoxV2GetAvailableV1.Request.FromString,
                    response_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_step__up__loot__box__pb2.StepUpLootBoxV2GetAvailableV1.Response.SerializeToString,
            ),
            'PurchaseV1': grpc.unary_unary_rpc_method_handler(
                    servicer.PurchaseV1,
                    request_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_step__up__loot__box__pb2.StepUpLootBoxV2PurchaseV1.Request.FromString,
                    response_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_step__up__loot__box__pb2.StepUpLootBoxV2PurchaseV1.Response.SerializeToString,
            ),
            'GetProbabilityV1': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProbabilityV1,
                    request_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_step__up__loot__box__pb2.StepUpLootBoxV2GetProbabilityV1.Request.FromString,
                    response_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_step__up__loot__box__pb2.StepUpLootBoxV2GetProbabilityV1.Response.SerializeToString,
            ),
            'GetDetailV1': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDetailV1,
                    request_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_step__up__loot__box__pb2.StepUpLootBoxV2GetDetailV1.Request.FromString,
                    response_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_step__up__loot__box__pb2.StepUpLootBoxV2GetDetailV1.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'takasho.schema.common_featureset.player_api.StepUpLootBoxV2', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class StepUpLootBoxV2(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAvailableV1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/takasho.schema.common_featureset.player_api.StepUpLootBoxV2/GetAvailableV1',
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_step__up__loot__box__pb2.StepUpLootBoxV2GetAvailableV1.Request.SerializeToString,
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_step__up__loot__box__pb2.StepUpLootBoxV2GetAvailableV1.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PurchaseV1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/takasho.schema.common_featureset.player_api.StepUpLootBoxV2/PurchaseV1',
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_step__up__loot__box__pb2.StepUpLootBoxV2PurchaseV1.Request.SerializeToString,
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_step__up__loot__box__pb2.StepUpLootBoxV2PurchaseV1.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetProbabilityV1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/takasho.schema.common_featureset.player_api.StepUpLootBoxV2/GetProbabilityV1',
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_step__up__loot__box__pb2.StepUpLootBoxV2GetProbabilityV1.Request.SerializeToString,
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_step__up__loot__box__pb2.StepUpLootBoxV2GetProbabilityV1.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDetailV1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/takasho.schema.common_featureset.player_api.StepUpLootBoxV2/GetDetailV1',
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_step__up__loot__box__pb2.StepUpLootBoxV2GetDetailV1.Request.SerializeToString,
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_step__up__loot__box__pb2.StepUpLootBoxV2GetDetailV1.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
