# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from takasho.schema.common_featureset.player_api import system_pb2 as takasho_dot_schema_dot_common__featureset_dot_player__api_dot_system__pb2


class SystemStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AuthorizeV3 = channel.unary_unary(
                '/takasho.schema.common_featureset.player_api.System/AuthorizeV3',
                request_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_system__pb2.SystemAuthorizeV3.Request.SerializeToString,
                response_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_system__pb2.SystemAuthorizeV3.Response.FromString,
                )
        self.AuthorizeV2 = channel.unary_unary(
                '/takasho.schema.common_featureset.player_api.System/AuthorizeV2',
                request_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_system__pb2.SystemAuthorizeV2.Request.SerializeToString,
                response_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_system__pb2.SystemAuthorizeV2.Response.FromString,
                )
        self.GetPlayerStatusV1 = channel.unary_unary(
                '/takasho.schema.common_featureset.player_api.System/GetPlayerStatusV1',
                request_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_system__pb2.SystemGetPlayerStatusV1.Request.SerializeToString,
                response_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_system__pb2.SystemGetPlayerStatusV1.Response.FromString,
                )
        self.GetPlayerStatusV2 = channel.unary_unary(
                '/takasho.schema.common_featureset.player_api.System/GetPlayerStatusV2',
                request_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_system__pb2.SystemGetPlayerStatusV2.Request.SerializeToString,
                response_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_system__pb2.SystemGetPlayerStatusV2.Response.FromString,
                )
        self.SetPlayerStatusV1 = channel.unary_unary(
                '/takasho.schema.common_featureset.player_api.System/SetPlayerStatusV1',
                request_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_system__pb2.SystemSetPlayerStatusV1.Request.SerializeToString,
                response_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_system__pb2.SystemSetPlayerStatusV1.Response.FromString,
                )
        self.DeletePlayerStatusV1 = channel.unary_unary(
                '/takasho.schema.common_featureset.player_api.System/DeletePlayerStatusV1',
                request_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_system__pb2.SystemDeletePlayerStatusV1.Request.SerializeToString,
                response_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_system__pb2.SystemDeletePlayerStatusV1.Response.FromString,
                )
        self.RecordLoginHistoryV1 = channel.unary_unary(
                '/takasho.schema.common_featureset.player_api.System/RecordLoginHistoryV1',
                request_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_system__pb2.SystemRecordLoginHistoryV1.Request.SerializeToString,
                response_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_system__pb2.SystemRecordLoginHistoryV1.Response.FromString,
                )
        self.GetWebTokenV1 = channel.unary_unary(
                '/takasho.schema.common_featureset.player_api.System/GetWebTokenV1',
                request_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_system__pb2.SystemGetWebTokenV1.Request.SerializeToString,
                response_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_system__pb2.SystemGetWebTokenV1.Response.FromString,
                )


class SystemServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AuthorizeV3(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AuthorizeV2(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPlayerStatusV1(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPlayerStatusV2(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetPlayerStatusV1(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePlayerStatusV1(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordLoginHistoryV1(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWebTokenV1(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SystemServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AuthorizeV3': grpc.unary_unary_rpc_method_handler(
                    servicer.AuthorizeV3,
                    request_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_system__pb2.SystemAuthorizeV3.Request.FromString,
                    response_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_system__pb2.SystemAuthorizeV3.Response.SerializeToString,
            ),
            'AuthorizeV2': grpc.unary_unary_rpc_method_handler(
                    servicer.AuthorizeV2,
                    request_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_system__pb2.SystemAuthorizeV2.Request.FromString,
                    response_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_system__pb2.SystemAuthorizeV2.Response.SerializeToString,
            ),
            'GetPlayerStatusV1': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlayerStatusV1,
                    request_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_system__pb2.SystemGetPlayerStatusV1.Request.FromString,
                    response_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_system__pb2.SystemGetPlayerStatusV1.Response.SerializeToString,
            ),
            'GetPlayerStatusV2': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlayerStatusV2,
                    request_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_system__pb2.SystemGetPlayerStatusV2.Request.FromString,
                    response_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_system__pb2.SystemGetPlayerStatusV2.Response.SerializeToString,
            ),
            'SetPlayerStatusV1': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPlayerStatusV1,
                    request_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_system__pb2.SystemSetPlayerStatusV1.Request.FromString,
                    response_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_system__pb2.SystemSetPlayerStatusV1.Response.SerializeToString,
            ),
            'DeletePlayerStatusV1': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePlayerStatusV1,
                    request_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_system__pb2.SystemDeletePlayerStatusV1.Request.FromString,
                    response_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_system__pb2.SystemDeletePlayerStatusV1.Response.SerializeToString,
            ),
            'RecordLoginHistoryV1': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordLoginHistoryV1,
                    request_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_system__pb2.SystemRecordLoginHistoryV1.Request.FromString,
                    response_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_system__pb2.SystemRecordLoginHistoryV1.Response.SerializeToString,
            ),
            'GetWebTokenV1': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWebTokenV1,
                    request_deserializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_system__pb2.SystemGetWebTokenV1.Request.FromString,
                    response_serializer=takasho_dot_schema_dot_common__featureset_dot_player__api_dot_system__pb2.SystemGetWebTokenV1.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'takasho.schema.common_featureset.player_api.System', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class System(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AuthorizeV3(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/takasho.schema.common_featureset.player_api.System/AuthorizeV3',
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_system__pb2.SystemAuthorizeV3.Request.SerializeToString,
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_system__pb2.SystemAuthorizeV3.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AuthorizeV2(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/takasho.schema.common_featureset.player_api.System/AuthorizeV2',
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_system__pb2.SystemAuthorizeV2.Request.SerializeToString,
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_system__pb2.SystemAuthorizeV2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPlayerStatusV1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/takasho.schema.common_featureset.player_api.System/GetPlayerStatusV1',
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_system__pb2.SystemGetPlayerStatusV1.Request.SerializeToString,
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_system__pb2.SystemGetPlayerStatusV1.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPlayerStatusV2(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/takasho.schema.common_featureset.player_api.System/GetPlayerStatusV2',
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_system__pb2.SystemGetPlayerStatusV2.Request.SerializeToString,
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_system__pb2.SystemGetPlayerStatusV2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetPlayerStatusV1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/takasho.schema.common_featureset.player_api.System/SetPlayerStatusV1',
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_system__pb2.SystemSetPlayerStatusV1.Request.SerializeToString,
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_system__pb2.SystemSetPlayerStatusV1.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeletePlayerStatusV1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/takasho.schema.common_featureset.player_api.System/DeletePlayerStatusV1',
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_system__pb2.SystemDeletePlayerStatusV1.Request.SerializeToString,
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_system__pb2.SystemDeletePlayerStatusV1.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RecordLoginHistoryV1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/takasho.schema.common_featureset.player_api.System/RecordLoginHistoryV1',
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_system__pb2.SystemRecordLoginHistoryV1.Request.SerializeToString,
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_system__pb2.SystemRecordLoginHistoryV1.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetWebTokenV1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/takasho.schema.common_featureset.player_api.System/GetWebTokenV1',
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_system__pb2.SystemGetWebTokenV1.Request.SerializeToString,
            takasho_dot_schema_dot_common__featureset_dot_player__api_dot_system__pb2.SystemGetWebTokenV1.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
